# Aula 5: Pandas e Numpy

Pandas e NumPy são duas bibliotecas muito importantes para se trabalhar com dados no python.

A biblioteca NumPy que é bastante utilizada na academia para programação numérica

Já o Pandas é utilizado predominantemente para Data Visualization e para Data Analysis

In [1]:
import numpy as np

#### Vetorização

NumPy é excelente para operações com vetores.

Operações do tipo:

- multiplicação matricial e outras operações de álgebra linear  
- vetores de número aleatório  
- aplicação de transformação (ex., seno, cosseno, log, ...)

Vamos tentar criar duas matrizes utilizando listas. Uma 3 x 3 e outra um vetor 1 x 3:

In [2]:
a = [[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]]
b = [1, 2, 3]
print(a)
print(b)
print(a*b)

[[5, 1, 3], [1, 1, 1], [1, 2, 1]]
[1, 2, 3]


TypeError: can't multiply sequence by non-int of type 'list'

Como podemos observar não conseguimos multiplicar essas duas listas. Analisando o erro fica claro que não podemos multiplicar uma lista por uma outra lista.

#### NumPy Arrays

A coisa mais importante que o NumPy define é um **array** N-dimensional formalmente denominado de [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

Podemos, então, recriar os vetores *a e b* como NumPy arrays e obter sua multiplicação da seguinte maneira:

In [3]:
a = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print(a*b)

[[5 2 9]
 [1 2 3]
 [1 4 3]]


In [4]:
type(a)

numpy.ndarray

Observe, porém, que a multiplicação foi realizada elemento por elemento.

Não obtivemos uma multiplicação matricial. Voltaremos a este problema mais tarde

NumPy arrays são parecidos com listas exceto que:

- As entradas devem ser *homogeneas* (elementos do mesmo tipo)  
- Esses tipos devem ser um dos tipos (`dtypes`) suportados pelo NumPy  


Os tipos mais importantes são:

- float64: 64 bit número em ponto flutuante  
- int64: 64 bit inteiro  
- bool:  8 bit True ou False  

Podemos obter o tipo de um objeto da seguinte maneira:

In [5]:
type(a), type(a[0][0])

(numpy.ndarray, numpy.int64)

In [6]:
a[0][0]

5

Para se obter a multiplicação matricial, devemod utilizar ".dot". Por exemplo:

In [7]:
print(a.dot(b))

[16  6  8]


Ainda assim nossa multiplicação não esta correta dado que estamos multiplicando uma matrix 3 x 3 por uma 1 x 3.

Redefinindo *b* da forma correta podemos obter a multiplicação matricial:

In [8]:
b = np.array([[1], [2], [3]])
print(b)
print("/n")
print(a.dot(b))

[[1]
 [2]
 [3]]
/n
[[16]
 [ 6]
 [ 8]]


Há uma outra maneira de se definir uma matriz. Essa envolve a utilização de [numpy.matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html)

Definindo-se dessa maneira as matrizes, podemos utilizar a operação produto (*), para multiplica-las:

In [9]:
sofi  = np.matrix([[5, 1 ,3], [1, 1 ,1], [1, 2 ,1]])

In [10]:
sofi.shape

(3, 3)

In [11]:
a

array([[5, 1, 3],
       [1, 1, 1],
       [1, 2, 1]])

In [12]:
a = np.matrix('[5, 1 ,3; 1, 1 ,1; 1, 2 ,1]')
b = np.matrix('[1; 2; 3]')
print(a)
a * b

[[5 1 3]
 [1 1 1]
 [1 2 1]]


matrix([[16],
        [ 6],
        [ 8]])

Podemos obter a transposta de diferentes maneiras:

In [13]:
a.transpose()

matrix([[5, 1, 1],
        [1, 1, 2],
        [3, 1, 1]])

In [14]:
a.T

matrix([[5, 1, 1],
        [1, 1, 2],
        [3, 1, 1]])

E a Inversa de uma matriz

In [15]:
a.getI()

matrix([[ 5.00000000e-01, -2.50000000e+00,  1.00000000e+00],
        [-3.08395285e-17, -1.00000000e+00,  1.00000000e+00],
        [-5.00000000e-01,  4.50000000e+00, -2.00000000e+00]])

In [16]:
a.I

matrix([[ 5.00000000e-01, -2.50000000e+00,  1.00000000e+00],
        [-3.08395285e-17, -1.00000000e+00,  1.00000000e+00],
        [-5.00000000e-01,  4.50000000e+00, -2.00000000e+00]])

No mais, NumPy arrays podem ser criados a partir de listas utilizando np.array

In [17]:
lista = [10, 20]
np.array(lista)

array([10, 20])

In [18]:
a

matrix([[5, 1, 3],
        [1, 1, 1],
        [1, 2, 1]])

In [19]:
a.mean()

1.7777777777777777

In [20]:
l = np.array(lista)

In [21]:
l.mean()

15.0

##### Métodos em um Array

In [22]:
a = np.array([5, 4, 3, 2, 1])
a

array([5, 4, 3, 2, 1])

In [23]:
a.sort()
a

array([1, 2, 3, 4, 5])

In [24]:
a.sum()

15

In [25]:
a.mean()

3.0

In [26]:
np.median(a)

3.0

In [27]:
a.max()

5

### PANDAS

Pandas será, provavelmente, a biblioteca mais utilizada por nós daqui em diante. Realizaremos quase todas as operações com dados nela. Importar, maniputar, salvar, estimar, ...

In [28]:
import pandas as pd

In [29]:
pd.read_csv("filmes.csv")

Dunkirk (2017) - IMDb  713K  7.8  \
0   Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
1                           Soul Surfer (2011) - IMDb   52K  7.0   
2                               Top Gun (1986) - IMDb  485K  6.9   
3                      Schindler's List (1993) - IMDb  1.4M  9.0   
4                                       403 Forbidden     -    -   
5                                       403 Forbidden     -    -   
6                                       403 Forbidden     -    -   
7                                       403 Forbidden     -    -   
8                                       403 Forbidden     -    -   
9                               Dunkirk (2017) - IMDb  713K  7.8   
10  Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
11                          Soul Surfer (2011) - IMDb   52K  7.0   
12                              Top Gun (1986) - IMDb  485K  6.9   
13                     Schindler's List (1993) - IMDb  1.4M  9.0   

    2023-09-25 15:45  
0   2023-09-25 15:45  
1   2023-09-25 15:45  
2   2023-09-25 15:45  
3   2023-09-25 15:45  
4   2023-09-25 15:49  
5   2023-09-25 15:49  
6   2023-09-25 15:49  
7   2023-09-25 15:49  
8   2023-09-25 15:49  
9   2023-09-25 15:50  
10  2023-09-25 15:50  
11  2023-09-25 15:50  
12  2023-09-25 15:50  
13  2023-09-25 15:50

Podemos ler um arquivo em formato CSV, por exemplo, e transforma-lo em uma base (dataframe).

In [30]:
df1 = pd.read_csv("filmes.csv", header = None, names=['nome', 'obs', 'rate', 'data']) 

In [31]:
df_gustavo = pd.read_csv("filmes.csv", header = None, names=['nome', 'obs', 'rate', 'data']) 

In [32]:
df1

nome   obs rate  \
0                               Dunkirk (2017) - IMDb  713K  7.8   
1   Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
2                           Soul Surfer (2011) - IMDb   52K  7.0   
3                               Top Gun (1986) - IMDb  485K  6.9   
4                      Schindler's List (1993) - IMDb  1.4M  9.0   
5                                       403 Forbidden     -    -   
6                                       403 Forbidden     -    -   
7                                       403 Forbidden     -    -   
8                                       403 Forbidden     -    -   
9                                       403 Forbidden     -    -   
10                              Dunkirk (2017) - IMDb  713K  7.8   
11  Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
12                          Soul Surfer (2011) - IMDb   52K  7.0   
13                              Top Gun (1986) - IMDb  485K  6.9   
14                     Schindler's List (1993) - IMDb  1.4M  9.0   

                data  
0   2023-09-25 15:45  
1   2023-09-25 15:45  
2   2023-09-25 15:45  
3   2023-09-25 15:45  
4   2023-09-25 15:45  
5   2023-09-25 15:49  
6   2023-09-25 15:49  
7   2023-09-25 15:49  
8   2023-09-25 15:49  
9   2023-09-25 15:49  
10  2023-09-25 15:50  
11  2023-09-25 15:50  
12  2023-09-25 15:50  
13  2023-09-25 15:50  
14  2023-09-25 15:50

In [33]:
df_gustavo

nome   obs rate  \
0                               Dunkirk (2017) - IMDb  713K  7.8   
1   Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
2                           Soul Surfer (2011) - IMDb   52K  7.0   
3                               Top Gun (1986) - IMDb  485K  6.9   
4                      Schindler's List (1993) - IMDb  1.4M  9.0   
5                                       403 Forbidden     -    -   
6                                       403 Forbidden     -    -   
7                                       403 Forbidden     -    -   
8                                       403 Forbidden     -    -   
9                                       403 Forbidden     -    -   
10                              Dunkirk (2017) - IMDb  713K  7.8   
11  Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5   
12                          Soul Surfer (2011) - IMDb   52K  7.0   
13                              Top Gun (1986) - IMDb  485K  6.9   
14                     Schindler's List (1993) - IMDb  1.4M  9.0   

                data  
0   2023-09-25 15:45  
1   2023-09-25 15:45  
2   2023-09-25 15:45  
3   2023-09-25 15:45  
4   2023-09-25 15:45  
5   2023-09-25 15:49  
6   2023-09-25 15:49  
7   2023-09-25 15:49  
8   2023-09-25 15:49  
9   2023-09-25 15:49  
10  2023-09-25 15:50  
11  2023-09-25 15:50  
12  2023-09-25 15:50  
13  2023-09-25 15:50  
14  2023-09-25 15:50

In [34]:
df1.to_csv('filmes_YARA.csv')

In [35]:
df1

nome   obs  rate        data
0                              Dunkirk (2017) - IMDb  648K   7.8  2022-09-19
1  Piratas do Caribe: A Vinganca de Salazar (2017...  309K   6.5  2022-09-19
2        Soul Surfer: Coragem de Viver (2011) - IMDb   50K   7.0  2022-09-19
3             Top Gun: Ases Indomaveis (1986) - IMDb  423K   6.9  2022-09-19
4                 A Lista de Schindler (1993) - IMDb  1.3M   9.0  2022-09-19
5                              Dunkirk (2017) - IMDb  648K   7.8         NaN
6  Piratas do Caribe: A Vinganca de Salazar (2017...  309K   6.5         NaN
7        Soul Surfer: Coragem de Viver (2011) - IMDb   50K   7.0         NaN
8             Top Gun: Ases Indomaveis (1986) - IMDb  423K   6.9         NaN
9                 A Lista de Schindler (1993) - IMDb  1.3M   9.0         NaN

In [36]:
yara = pd.read_csv("filmes_YARA.csv")

In [37]:
yara

Unnamed: 0                                               nome   obs  rate  \
0           0                              Dunkirk (2017) - IMDb  648K   7.8   
1           1  Piratas do Caribe: A Vinganca de Salazar (2017...  309K   6.5   
2           2        Soul Surfer: Coragem de Viver (2011) - IMDb   50K   7.0   
3           3             Top Gun: Ases Indomaveis (1986) - IMDb  423K   6.9   
4           4                 A Lista de Schindler (1993) - IMDb  1.3M   9.0   
5           5                              Dunkirk (2017) - IMDb  648K   7.8   
6           6  Piratas do Caribe: A Vinganca de Salazar (2017...  309K   6.5   
7           7        Soul Surfer: Coragem de Viver (2011) - IMDb   50K   7.0   
8           8             Top Gun: Ases Indomaveis (1986) - IMDb  423K   6.9   
9           9                 A Lista de Schindler (1993) - IMDb  1.3M   9.0   

         data  
0  2022-09-19  
1  2022-09-19  
2  2022-09-19  
3  2022-09-19  
4  2022-09-19  
5         NaN  
6         NaN  
7         NaN  
8         NaN  
9         NaN

Salvar uma base de dados em csv.

In [29]:
df1.to_csv('ex_save_filmes.csv', index=False)

In [40]:
df1

nome        obs  rate
0                               Dunkirk (2017) - IMDb    543.268   7.9
1   Piratas do Caribe: A Vinganca de Salazar (2017...    259.112   6.6
2         Soul Surfer: Coragem de Viver (2011) - IMDb     45.257   7.0
3              Top Gun: Ases Indomaveis (1986) - IMDb    291.570   6.9
4                  A Lista de Schindler (1993) - IMDb  1.198.580   8.9
5                               Dunkirk (2017) - IMDb    543.268   7.9
6   Piratas do Caribe: A Vinganca de Salazar (2017...    259.112   6.6
7         Soul Surfer: Coragem de Viver (2011) - IMDb     45.257   7.0
8              Top Gun: Ases Indomaveis (1986) - IMDb    291.570   6.9
9                  A Lista de Schindler (1993) - IMDb  1.198.580   8.9
10                   A Lista de Gustavo (2020) - IMDb  1.198.580   8.9

In [32]:
df1.to_pickle('dados.pkl')

In [33]:
filmes = pd.read_pickle("dados.pkl")

In [34]:
filmes

nome        obs  rate
0                               Dunkirk (2017) - IMDb    543.268   7.9
1   Piratas do Caribe: A Vinganca de Salazar (2017...    259.112   6.6
2         Soul Surfer: Coragem de Viver (2011) - IMDb     45.257   7.0
3              Top Gun: Ases Indomaveis (1986) - IMDb    291.570   6.9
4                  A Lista de Schindler (1993) - IMDb  1.198.580   8.9
5                               Dunkirk (2017) - IMDb    543.268   7.9
6   Piratas do Caribe: A Vinganca de Salazar (2017...    259.112   6.6
7         Soul Surfer: Coragem de Viver (2011) - IMDb     45.257   7.0
8              Top Gun: Ases Indomaveis (1986) - IMDb    291.570   6.9
9                  A Lista de Schindler (1993) - IMDb  1.198.580   8.9
10                   A Lista de Gustavo (2020) - IMDb  1.198.580   8.9

O mesmo pode-se aplicar para o [pickle](). Podemos ler e salvar bases de dados em pickle

In [39]:
dfp = pd.read_pickle("dados_placas.pkl")

In [37]:
dfp

['KFD0001',
 'KFD0002',
 'KFD0003',
 'KFD0004',
 'KFD0005',
 'KFD0006',
 'KFD0007',
 'KFD0008',
 'KFD0009',
 'KFD0010',
 'KFD0011',
 'KFD0012',
 'KFD0013',
 'KFD0014',
 'KFD0015',
 'KFD0016',
 'KFD0017',
 'KFD0018',
 'KFD0019',
 'KFD0020',
 'KFD0021',
 'KFD0022',
 'KFD0023',
 'KFD0024',
 'KFD0025',
 'KFD0026',
 'KFD0027',
 'KFD0028',
 'KFD0029',
 'KFD0030',
 'KFD0031',
 'KFD0032',
 'KFD0033',
 'KFD0034',
 'KFD0035',
 'KFD0036',
 'KFD0037',
 'KFD0038',
 'KFD0039',
 'KFD0040',
 'KFD0041',
 'KFD0042',
 'KFD0043',
 'KFD0044',
 'KFD0045',
 'KFD0046',
 'KFD0047',
 'KFD0048',
 'KFD0049',
 'KFD0050',
 'KFD0051',
 'KFD0052',
 'KFD0053',
 'KFD0054',
 'KFD0055',
 'KFD0056',
 'KFD0057',
 'KFD0058',
 'KFD0059',
 'KFD0060',
 'KFD0061',
 'KFD0062',
 'KFD0063',
 'KFD0064',
 'KFD0065',
 'KFD0066',
 'KFD0067',
 'KFD0068',
 'KFD0069',
 'KFD0070',
 'KFD0071',
 'KFD0072',
 'KFD0073',
 'KFD0074',
 'KFD0075',
 'KFD0076',
 'KFD0077',
 'KFD0078',
 'KFD0079',
 'KFD0080',
 'KFD0081',
 'KFD0082',
 'KFD0083',
 'KF

In [40]:
dfp_paulo = pd.DataFrame(dfp)

In [43]:
dfp_paulo

0
0        KFD0001
1        KFD0002
2        KFD0003
3        KFD0004
4        KFD0005
...          ...
3319663  PGZ9995
3319664  PGZ9996
3319665  PGZ9997
3319666  PGZ9998
3319667  PGZ9999

[3319668 rows x 1 columns]

In [34]:
pd.DataFrame([27,43,12,34,56])

0
0  27
1  43
2  12
3  34
4  56

In [35]:
pd.DataFrame([{"nome":"Luiza", "idade":23},{"nome":"Jessycka", "idade":21}])

nome  idade
0     Luiza     23
1  Jessycka     21

In [36]:
import numpy as np

In [43]:
np.random.seed(348)

In [38]:
np.random.randn(10, 5)

array([[-0.74514763, -1.46266894,  1.54404756, -0.31482662,  1.36373213],
       [ 0.32085106,  1.29412995,  0.0143156 ,  0.14287208, -0.41008282],
       [-1.12083216, -0.55690501,  1.63577838, -1.03892929, -0.29886137],
       [-0.39862243, -0.33556923, -1.24802003, -0.67311139,  0.60756303],
       [ 0.86236012, -1.7406042 ,  0.29265206, -0.66594992,  0.64543729],
       [-1.26187917,  0.78069167,  0.86589102, -0.73428542, -0.93107143],
       [ 0.89830949,  0.43982177,  1.51167026,  1.47126806, -0.41588905],
       [-0.5301987 , -1.49244846,  0.97906741, -0.27851437, -0.50744542],
       [-0.36497737, -0.6466633 ,  0.36642132,  0.69406482,  1.81706187],
       [-0.41561977,  1.02982406,  0.54369807, -1.03696244, -0.09391205]])

In [23]:
dfp.to_pickle("dados1.pkl")

Ou gerar uma base de dados com números aleatórios

In [40]:
df2 = pd.DataFrame(np.random.randn(10, 5))

In [35]:
#seed = 37987384

In [41]:
df2

0         1         2         3         4
0 -0.745148 -1.462669  1.544048 -0.314827  1.363732
1  0.320851  1.294130  0.014316  0.142872 -0.410083
2 -1.120832 -0.556905  1.635778 -1.038929 -0.298861
3 -0.398622 -0.335569 -1.248020 -0.673111  0.607563
4  0.862360 -1.740604  0.292652 -0.665950  0.645437
5 -1.261879  0.780692  0.865891 -0.734285 -0.931071
6  0.898309  0.439822  1.511670  1.471268 -0.415889
7 -0.530199 -1.492448  0.979067 -0.278514 -0.507445
8 -0.364977 -0.646663  0.366421  0.694065  1.817062
9 -0.415620  1.029824  0.543698 -1.036962 -0.093912

Array 10-por-5 de amostras de uma N(0, 1):

In [42]:
np.random.randn(10, 5)

array([[ 2.52167367,  1.61975886, -0.82022577, -0.48772754, -0.09869889],
       [-1.83654245,  0.55535121, -0.88008513,  0.77704237,  1.75933062],
       [-0.75727009,  0.25917791,  0.50515296, -0.42478323,  0.15291093],
       [ 0.47856111,  0.71549107,  0.83473425, -0.48329803, -0.31592175],
       [-0.94085722,  0.04387738,  0.9080636 ,  0.81681172, -1.60632205],
       [ 0.26751739,  2.27733156, -0.57088182, -0.74022969,  0.83072685],
       [-0.5958215 ,  0.58772034,  0.10628872, -0.5407303 , -0.62582666],
       [-0.38944248,  0.02037429,  0.23342369, -1.71760353, -0.29137084],
       [-0.84085245,  1.11505627,  0.72228551, -0.28326351,  0.16359511],
       [ 1.13915731, -1.18333203, -1.51778934, -0.65531438,  1.00987297]])

In [29]:
an = np.random.randn(10, 5)

In [30]:
pd.DataFrame(an)

0         1         2         3         4
0 -0.415811  0.634043 -0.320084 -1.035141 -1.472318
1 -0.542063 -0.176143 -1.338999  1.164823  1.651221
2  0.204946  0.519608 -0.064065 -1.443523 -0.982411
3 -1.420311  0.993670  0.564678  0.244036 -1.161996
4  0.623735 -1.096172 -0.290833 -0.643554 -0.844381
5  1.050471  0.735425  0.435364 -0.240895 -1.215186
6  0.722506  1.076963  0.545667 -1.635789 -1.275542
7 -0.289325 -0.238281  0.952617 -0.144314  0.437175
8  0.897783 -0.674219  1.179446  1.552766  1.230427
9  0.984672  0.604761 -0.755868 -1.388132  0.026702

Array 10-por-5 de amostras de uma N(3, 6.25):

In [44]:
2.5 * np.random.randn(10, 5) + 3

array([[ 1.13713092, -0.65667234,  6.86011889,  2.21293345,  6.40933034],
       [ 3.80212764,  6.23532489,  3.03578901,  3.3571802 ,  1.97479295],
       [ 0.1979196 ,  1.60773748,  7.08944594,  0.40267677,  2.25284657],
       [ 2.00344392,  2.16107692, -0.12005008,  1.31722153,  4.51890758],
       [ 5.1559003 , -1.35151051,  3.73163015,  1.33512521,  4.61359322],
       [-0.15469793,  4.95172918,  5.16472754,  1.16428645,  0.67232143],
       [ 5.24577372,  4.09955443,  6.77917565,  6.67817015,  1.96027738],
       [ 1.67450324, -0.73112115,  5.44766853,  2.30371409,  1.73138645],
       [ 2.08755658,  1.38334175,  3.91605329,  4.73516206,  7.54265467],
       [ 1.96095057,  5.57456015,  4.35924518,  0.40759389,  2.76521989]])

In [45]:
df_N3 = pd.DataFrame(2.5 * np.random.randn(1000000, 5) + 3)

In [46]:
df_N3

0         1         2         3         4
0       9.304184  7.049397  0.949436  1.780681  2.753253
1      -1.591356  4.388378  0.799787  4.942606  7.398327
2       1.106825  3.647945  4.262882  1.938042  3.382277
3       4.196403  4.788728  5.086836  1.791755  2.210196
4       0.647857  3.109693  5.270159  5.042029 -1.015805
...          ...       ...       ...       ...       ...
999995  4.685775  7.308961  4.186600  2.307876  5.008472
999996  3.515232  1.536897  2.499319  9.574790  3.570077
999997  2.685452  7.616182  7.357554  2.381461  5.504153
999998  4.703496  2.480500  5.575493  2.442857  7.280765
999999  3.540161  4.075161  2.435527  4.013901  5.451683

[1000000 rows x 5 columns]

In [47]:
data = {
'País': ['Bélgica', 'Índia', 'Brasil'],
'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
'População': [123465, 456789, 987654]
}

In [48]:
data

{'País': ['Bélgica', 'Índia', 'Brasil'],
 'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
 'População': [123465, 456789, 987654]}

In [50]:
data['Capital']

['Bruxelas', 'Nova Delhi', 'Brasília']

In [51]:
df3 = pd.DataFrame(data, columns=['País','Capital','População'])

In [52]:
df3

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

Podemos criar a mesma base através de uma lista de vários json's

In [53]:
data = [{"País":"Bélgica","Capital":"Bruxelas","População":123465},
        {"País":"Índia","Capital":"Nova Delhi","População":456789},
        {"País":"Brasil","Capital":"Brasília","População":987654}]

In [54]:
data

[{'País': 'Bélgica', 'Capital': 'Bruxelas', 'População': 123465},
 {'País': 'Índia', 'Capital': 'Nova Delhi', 'População': 456789},
 {'País': 'Brasil', 'Capital': 'Brasília', 'População': 987654}]

In [81]:
df4 = pd.DataFrame(data)

In [82]:
df4

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

In [57]:
df4.drop([0,1], inplace=True)

In [58]:
df4

País   Capital  População
2  Brasil  Brasília     987654

É possível apagar linhas de um dataframe através do índice

In [59]:
df3 = df3.drop([0, 1], axis=0)

In [60]:
df3

País   Capital  População
2  Brasil  Brasília     987654

In [61]:
df3.drop(["Capital","População"],axis=1)

País
2  Brasil

In [62]:
df3.to_csv("p.csv")

In [63]:
h = pd.read_csv("p.csv")

In [64]:
h

Unnamed: 0    País   Capital  População
0           2  Brasil  Brasília     987654

In [65]:
df3

País   Capital  População
2  Brasil  Brasília     987654

In [66]:
df3.reset_index()

index    País   Capital  População
0      2  Brasil  Brasília     987654

In [67]:
np

<module 'numpy' from '/opt/miniconda3/lib/python3.9/site-packages/numpy/__init__.py'>

In [68]:
np.nan

nan

In [69]:
g = [('bird', 389.0),('bird', 24.0),('mammal', 80.5),('mammal', np.nan)]

In [70]:
g

[('bird', 389.0), ('bird', 24.0), ('mammal', 80.5), ('mammal', nan)]

In [71]:
pd.DataFrame(g)

0      1
0    bird  389.0
1    bird   24.0
2  mammal   80.5
3  mammal    NaN

In [72]:
df = pd.DataFrame(g,index=['falcon', 'parrot', 'lion', 'monkey'],columns=('class', 'max_speed'))

In [73]:
df

class  max_speed
falcon    bird      389.0
parrot    bird       24.0
lion    mammal       80.5
monkey  mammal        NaN

In [74]:
joao = [('falcon', 389.0),('parrot', 24.0),('lion', 80.5),('monkey', np.nan)]

In [75]:
df = pd.DataFrame(joao,index=['bird', 'bird', 'mammal', 'mammal'],columns=('class', 'max_speed'))

In [76]:
df

class  max_speed
bird    falcon      389.0
bird    parrot       24.0
mammal    lion       80.5
mammal  monkey        NaN

In [77]:
df.reset_index()

index   class  max_speed
0    bird  falcon      389.0
1    bird  parrot       24.0
2  mammal    lion       80.5
3  mammal  monkey        NaN

In [83]:
df3 = df4

In [84]:
df3

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

In [85]:
df3[['População','Capital']]

População     Capital
0     123465    Bruxelas
1     456789  Nova Delhi
2     987654    Brasília

In [86]:
df3['País']

0    Bélgica
1      Índia
2     Brasil
Name: País, dtype: object

Ou remover colunas utilizando o argumento axis=1

In [87]:
df3.drop(['País','População'], axis=1)

Capital
0    Bruxelas
1  Nova Delhi
2    Brasília

Coletando informações básicas sobre o DataFrame: 

Quantidade de linhas e colunas do DataFrame

In [88]:
df3.shape

(3, 3)

Descrição do Index

In [89]:
df3.index 

RangeIndex(start=0, stop=3, step=1)

In [90]:
list(df3)

['País', 'Capital', 'População']

Colunas presentes no DataFrame

In [91]:
df3.columns

Index(['País', 'Capital', 'População'], dtype='object')

Contagem de dados não-nulos

In [92]:
df3.count()

País         3
Capital      3
População    3
dtype: int64

In [93]:
c = df3.count()

In [94]:
c

País         3
Capital      3
População    3
dtype: int64

In [95]:
df3

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

Criando uma nova coluna em um DataFrame

In [96]:
df3['Nova_Coluna'] = 0

In [97]:
df3['Nova_Coluna1'] = df3['População']**2

In [98]:
df3

País     Capital  População  Nova_Coluna  Nova_Coluna1
0  Bélgica    Bruxelas     123465            0   15243606225
1    Índia  Nova Delhi     456789            0  208656190521
2   Brasil    Brasília     987654            0  975460423716

In [99]:
df3['Nova_Coluna'] = 10

In [100]:
df3

País     Capital  População  Nova_Coluna  Nova_Coluna1
0  Bélgica    Bruxelas     123465           10   15243606225
1    Índia  Nova Delhi     456789           10  208656190521
2   Brasil    Brasília     987654           10  975460423716

In [101]:
df3.columns

Index(['País', 'Capital', 'População', 'Nova_Coluna', 'Nova_Coluna1'], dtype='object')

Renomeando colunas de um DataFrame

Se seu DataFrame possui 3 colunas, passe 3 novos valores em uma lista

In [102]:
df3.columns = ['Coluna 1', 'Coluna 2', 'Coluna 3', 'Coluna 4','Coluna 5']

In [103]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5
0  Bélgica    Bruxelas    123465        10   15243606225
1    Índia  Nova Delhi    456789        10  208656190521
2   Brasil    Brasília    987654        10  975460423716

In [104]:
df3.rename(columns={"Coluna 4": "Sofia"})

Coluna 1    Coluna 2  Coluna 3  Sofia      Coluna 5
0  Bélgica    Bruxelas    123465     10   15243606225
1    Índia  Nova Delhi    456789     10  208656190521
2   Brasil    Brasília    987654     10  975460423716

In [105]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5
0  Bélgica    Bruxelas    123465        10   15243606225
1    Índia  Nova Delhi    456789        10  208656190521
2   Brasil    Brasília    987654        10  975460423716

Resumo dos dados

Soma dos valores de um DataFrame

In [106]:
df3.sum()

Coluna 1            BélgicaÍndiaBrasil
Coluna 2    BruxelasNova DelhiBrasília
Coluna 3                       1567908
Coluna 4                            30
Coluna 5                 1199360220462
dtype: object

Menor valor de um DataFrame

In [107]:
df3.min()

Coluna 1         Brasil
Coluna 2       Brasília
Coluna 3         123465
Coluna 4             10
Coluna 5    15243606225
dtype: object

Maior valor

In [108]:
df3.max()

Coluna 1           Índia
Coluna 2      Nova Delhi
Coluna 3          987654
Coluna 4              10
Coluna 5    975460423716
dtype: object

In [109]:
df3['Coluna 4'].sum()

30

In [110]:
df3['Coluna 3']

0    123465
1    456789
2    987654
Name: Coluna 3, dtype: int64

Index do menor valor

In [111]:
df3["Coluna 3"].idxmin()

0

Index do maior valor

In [112]:
df3["Coluna 3"].idxmax()

2

In [113]:
df3.describe()

Coluna 3  Coluna 4      Coluna 5
count       3.000000       3.0  3.000000e+00
mean   522636.000000      10.0  3.997867e+11
std    435841.172317       0.0  5.078408e+11
min    123465.000000      10.0  1.524361e+10
25%    290127.000000      10.0  1.119499e+11
50%    456789.000000      10.0  2.086562e+11
75%    722221.500000      10.0  5.920583e+11
max    987654.000000      10.0  9.754604e+11

In [114]:
df_N3.describe()

0               1               2               3  \
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000   
mean         2.998534        2.998239        2.998057        2.996290   
std          2.499591        2.498001        2.499250        2.497694   
min         -8.750270       -9.146553       -8.548470       -9.068712   
25%          1.311865        1.311910        1.310136        1.309412   
50%          2.999539        2.996848        3.001022        2.996453   
75%          4.685346        4.682244        4.685295        4.682198   
max         15.125428       15.392178       14.971129       15.054953   

                    4  
count  1000000.000000  
mean         3.000458  
std          2.499488  
min         -9.295679  
25%          1.314885  
50%          3.003181  
75%          4.685286  
max         13.872244

Resumo estatístico do DataFrame, com quartis, mediana, etc.

In [115]:
lipe = df3.describe()

In [116]:
lipe.to_latex()

/var/folders/j0/5s6rknpd2j1bczb130mw14cm0000gn/T/ipykernel_77057/440450807.py:1: FutureWarning: In future versions `DataFrame.to_latex` is expected to utilise the base implementation of `Styler.to_latex` for formatting and rendering. The arguments signature may therefore change. It is recommended instead to use `DataFrame.style.to_latex` which also contains additional functionality.
  lipe.to_latex()


'\\begin{tabular}{lrrr}\n\\toprule\n{} &       Coluna 3 &  Coluna 4 &      Coluna 5 \\\\\n\\midrule\ncount &       3.000000 &       3.0 &  3.000000e+00 \\\\\nmean  &  522636.000000 &      10.0 &  3.997867e+11 \\\\\nstd   &  435841.172317 &       0.0 &  5.078408e+11 \\\\\nmin   &  123465.000000 &      10.0 &  1.524361e+10 \\\\\n25\\%   &  290127.000000 &      10.0 &  1.119499e+11 \\\\\n50\\%   &  456789.000000 &      10.0 &  2.086562e+11 \\\\\n75\\%   &  722221.500000 &      10.0 &  5.920583e+11 \\\\\nmax   &  987654.000000 &      10.0 &  9.754604e+11 \\\\\n\\bottomrule\n\\end{tabular}\n'

Vamos utilizar nossa base gerada a partir de uma Normal com média 3 e desvio 2.5

In [117]:
df_N3.describe()

0               1               2               3  \
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000   
mean         2.998534        2.998239        2.998057        2.996290   
std          2.499591        2.498001        2.499250        2.497694   
min         -8.750270       -9.146553       -8.548470       -9.068712   
25%          1.311865        1.311910        1.310136        1.309412   
50%          2.999539        2.996848        3.001022        2.996453   
75%          4.685346        4.682244        4.685295        4.682198   
max         15.125428       15.392178       14.971129       15.054953   

                    4  
count  1000000.000000  
mean         3.000458  
std          2.499488  
min         -9.295679  
25%          1.314885  
50%          3.003181  
75%          4.685286  
max         13.872244

In [118]:
df_N3.describe(percentiles=[.10, .25, .5, .65 , .75])

0               1               2               3  \
count  1000000.000000  1000000.000000  1000000.000000  1000000.000000   
mean         2.998534        2.998239        2.998057        2.996290   
std          2.499591        2.498001        2.499250        2.497694   
min         -8.750270       -9.146553       -8.548470       -9.068712   
10%         -0.200924       -0.199529       -0.205266       -0.209119   
25%          1.311865        1.311910        1.310136        1.309412   
50%          2.999539        2.996848        3.001022        2.996453   
65%          3.961957        3.958508        3.964285        3.958027   
75%          4.685346        4.682244        4.685295        4.682198   
max         15.125428       15.392178       14.971129       15.054953   

                    4  
count  1000000.000000  
mean         3.000458  
std          2.499488  
min         -9.295679  
10%         -0.204117  
25%          1.314885  
50%          3.003181  
65%          3.964657  
75%          4.685286  
max         13.872244

Média dos valores

In [119]:
df3.mean()

/var/folders/j0/5s6rknpd2j1bczb130mw14cm0000gn/T/ipykernel_77057/3891983329.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df3.mean()


Coluna 3    5.226360e+05
Coluna 4    1.000000e+01
Coluna 5    3.997867e+11
dtype: float64

Mediana dos valores

In [120]:
df3.median()

/var/folders/j0/5s6rknpd2j1bczb130mw14cm0000gn/T/ipykernel_77057/3131045010.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df3.median()


Coluna 3    4.567890e+05
Coluna 4    1.000000e+01
Coluna 5    2.086562e+11
dtype: float64

#### Funções Lambda

A função lambda é uma função anonima

Ela pode receber qualquer número de argumentos, mas só pode ter uma expressão.


In [121]:
def teste(a):
    b = a*3
    return b

In [122]:
teste(4)

12

In [123]:
(lambda a : a * 3)(4)

12

In [124]:
(lambda a : a + 10)(10)

20

In [125]:
x = lambda a : a + 10
x(10)

20

In [126]:
d = lambda x:  x[0] - 2 * x[1] + 2

In [127]:
d([1,2])

-1

In [128]:
x = lambda a, b : a * b

In [129]:
x(5, 6)

30

In [130]:
def myfunc(n):
    return lambda a : a * n

In [131]:
mydoubler = myfunc(2)

In [132]:
mydoubler

<function __main__.myfunc.<locals>.<lambda>(a)>

In [133]:
mydoubler(11)

22

In [134]:
mytripler = myfunc(3)

In [135]:
mytripler(11)

33

In [136]:
myquad = myfunc(4)

In [138]:
myquad(11)

44

In [139]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5
0  Bélgica    Bruxelas    123465        10   15243606225
1    Índia  Nova Delhi    456789        10  208656190521
2   Brasil    Brasília    987654        10  975460423716

In [140]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5
0  Bélgica    Bruxelas    123465        10   15243606225
1    Índia  Nova Delhi    456789        10  208656190521
2   Brasil    Brasília    987654        10  975460423716

In [141]:
df3['Col4'] = 10

In [142]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Col4
0  Bélgica    Bruxelas    123465        10   15243606225    10
1    Índia  Nova Delhi    456789        10  208656190521    10
2   Brasil    Brasília    987654        10  975460423716    10

Aplicando funções:

Aplicando uma função que substitui 0 por 1

In [143]:
df3.apply(lambda x: x.replace(10, 1))

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Col4
0  Bélgica    Bruxelas    123465         1   15243606225     1
1    Índia  Nova Delhi    456789         1  208656190521     1
2   Brasil    Brasília    987654         1  975460423716     1

Ordenando valores:

Ordenando em ordem crescente

In [146]:
df3.columns = ['Coluna 1','Coluna 2','Coluna 3','Coluna 4', 'Coluna 5', 'Coluna 6']

In [147]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6
0  Bélgica    Bruxelas    123465        10   15243606225        10
1    Índia  Nova Delhi    456789        10  208656190521        10
2   Brasil    Brasília    987654        10  975460423716        10

In [148]:
df3.sort_values(by='Coluna 3')

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6
0  Bélgica    Bruxelas    123465        10   15243606225        10
1    Índia  Nova Delhi    456789        10  208656190521        10
2   Brasil    Brasília    987654        10  975460423716        10

Ordenando em ordem decrescente

In [149]:
df3.sort_values(by='Coluna 3',ascending=False)

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6
2   Brasil    Brasília    987654        10  975460423716        10
1    Índia  Nova Delhi    456789        10  208656190521        10
0  Bélgica    Bruxelas    123465        10   15243606225        10

Selecionando valores: 

Selecionando a primeira linha da coluna país

loc: seleciona linhas (ou colunas) com labels particulares do index.

iloc: seleciona linhas (ou colunas) em posições particulares do index (assume número inteiro).

In [150]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6
0  Bélgica    Bruxelas    123465        10   15243606225        10
1    Índia  Nova Delhi    456789        10  208656190521        10
2   Brasil    Brasília    987654        10  975460423716        10

In [151]:
df3['NC'] = 100

In [152]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

In [153]:
df3.index

RangeIndex(start=0, stop=3, step=1)

In [154]:
df3.loc[0]

Coluna 1        Bélgica
Coluna 2       Bruxelas
Coluna 3         123465
Coluna 4             10
Coluna 5    15243606225
Coluna 6             10
NC                  100
Name: 0, dtype: object

In [155]:
df3.iloc[0:2]

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100

In [156]:
dfp = df3.drop(1)

In [157]:
dfp

Coluna 1  Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica  Bruxelas    123465        10   15243606225        10  100
2   Brasil  Brasília    987654        10  975460423716        10  100

In [158]:
dfp.iloc[1]

Coluna 1          Brasil
Coluna 2        Brasília
Coluna 3          987654
Coluna 4              10
Coluna 5    975460423716
Coluna 6              10
NC                   100
Name: 2, dtype: object

In [159]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

In [160]:
df3["Coluna 1"] == 'Brasil'

0    False
1    False
2     True
Name: Coluna 1, dtype: bool

In [161]:
df3[df3["Coluna 1"] == 'Brasil']

Coluna 1  Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
2   Brasil  Brasília    987654        10  975460423716        10  100

In [162]:
df3[df3["Coluna 1"] == 'Bélgica']

Coluna 1  Coluna 2  Coluna 3  Coluna 4     Coluna 5  Coluna 6   NC
0  Bélgica  Bruxelas    123465        10  15243606225        10  100

In [163]:
df3[df3["Coluna 3"] >= 123475]

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

In [164]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

In [165]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0  Bélgica    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

In [166]:
df3.loc[0]

Coluna 1        Bélgica
Coluna 2       Bruxelas
Coluna 3         123465
Coluna 4             10
Coluna 5    15243606225
Coluna 6             10
NC                  100
Name: 0, dtype: object

In [167]:
df3.loc[0, 'Coluna 1'] = "Kyev"

In [168]:
df3.iloc[0]['Coluna 3']

123465

In [169]:
df3[['Coluna 3','Coluna 2']]

Coluna 3    Coluna 2
0    123465    Bruxelas
1    456789  Nova Delhi
2    987654    Brasília

In [170]:
df3

Coluna 1    Coluna 2  Coluna 3  Coluna 4      Coluna 5  Coluna 6   NC
0     Kyev    Bruxelas    123465        10   15243606225        10  100
1    Índia  Nova Delhi    456789        10  208656190521        10  100
2   Brasil    Brasília    987654        10  975460423716        10  100

Suponha, agora, que queremos importar a base de dados AUTO em ".dta".

In [171]:
df4 = pd.read_stata("auto.dta")

In [172]:
df4

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
0     AMC Concord   4099   22    3.0       2.5     11    2930     186    40   
1       AMC Pacer   4749   17    3.0       3.0     11    3350     173    40   
2      AMC Spirit   3799   22    NaN       3.0     12    2640     168    35   
3   Buick Century   4816   20    3.0       4.5     16    3250     196    40   
4   Buick Electra   7827   15    4.0       4.0     20    4080     222    43   
..            ...    ...  ...    ...       ...    ...     ...     ...   ...   
69      VW Dasher   7140   23    4.0       2.5     12    2160     172    36   
70      VW Diesel   5397   41    5.0       3.0     15    2040     155    35   
71      VW Rabbit   4697   25    4.0       3.0     15    1930     155    35   
72    VW Scirocco   6850   25    4.0       2.0     16    1990     156    36   
73      Volvo 260  11995   17    5.0       2.5     14    3170     193    37   

    displacement  gear_ratio   foreign  
0            121        3.58  Domestic  
1            258        2.53  Domestic  
2            121        3.08  Domestic  
3            196        2.93  Domestic  
4            350        2.41  Domestic  
..           ...         ...       ...  
69            97        3.74   Foreign  
70            90        3.78   Foreign  
71            89        3.78   Foreign  
72            97        3.78   Foreign  
73           163        2.98   Foreign  

[74 rows x 12 columns]

In [173]:
list(df4)

['make',
 'price',
 'mpg',
 'rep78',
 'headroom',
 'trunk',
 'weight',
 'length',
 'turn',
 'displacement',
 'gear_ratio',
 'foreign']

In [174]:
df4.dtypes

make              object
price              int16
mpg                int16
rep78            float64
headroom         float32
trunk              int16
weight             int16
length             int16
turn               int16
displacement       int16
gear_ratio       float32
foreign         category
dtype: object

In [175]:
df4.columns

Index(['make', 'price', 'mpg', 'rep78', 'headroom', 'trunk', 'weight',
       'length', 'turn', 'displacement', 'gear_ratio', 'foreign'],
      dtype='object')

In [176]:
df4.head(7)

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
0    AMC Concord   4099   22    3.0       2.5     11    2930     186    40   
1      AMC Pacer   4749   17    3.0       3.0     11    3350     173    40   
2     AMC Spirit   3799   22    NaN       3.0     12    2640     168    35   
3  Buick Century   4816   20    3.0       4.5     16    3250     196    40   
4  Buick Electra   7827   15    4.0       4.0     20    4080     222    43   
5  Buick LeSabre   5788   18    3.0       4.0     21    3670     218    43   
6     Buick Opel   4453   26    NaN       3.0     10    2230     170    34   

   displacement  gear_ratio   foreign  
0           121        3.58  Domestic  
1           258        2.53  Domestic  
2           121        3.08  Domestic  
3           196        2.93  Domestic  
4           350        2.41  Domestic  
5           231        2.73  Domestic  
6           304        2.87  Domestic

In [177]:
df4.tail()

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
69    VW Dasher   7140   23    4.0       2.5     12    2160     172    36   
70    VW Diesel   5397   41    5.0       3.0     15    2040     155    35   
71    VW Rabbit   4697   25    4.0       3.0     15    1930     155    35   
72  VW Scirocco   6850   25    4.0       2.0     16    1990     156    36   
73    Volvo 260  11995   17    5.0       2.5     14    3170     193    37   

    displacement  gear_ratio  foreign  
69            97        3.74  Foreign  
70            90        3.78  Foreign  
71            89        3.78  Foreign  
72            97        3.78  Foreign  
73           163        2.98  Foreign

In [178]:
df4.sample(n=10)

make  price  mpg  rep78  headroom  trunk  weight  length  \
23       Ford Fiesta   4389   28    4.0       1.5      9    1800     147   
55        Datsun 200   6229   23    4.0       1.5      6    2370     170   
40     Olds Toronado  10371   16    3.0       3.5     17    4030     206   
42       Plym. Champ   4425   34    5.0       2.5     11    1800     157   
10      Cad. Deville  11385   14    3.0       4.0     20    4330     221   
21      Dodge Magnum   5886   16    2.0       4.0     17    3600     206   
18        Chev. Nova   3955   19    3.0       3.5     13    3430     197   
27  Linc. Versailles  13466   14    3.0       3.5     15    3830     201   
53          Audi Fox   6295   23    3.0       2.5     11    2070     174   
71         VW Rabbit   4697   25    4.0       3.0     15    1930     155   

    turn  displacement  gear_ratio   foreign  
23    33            98        3.15  Domestic  
55    35           119        3.89   Foreign  
40    43           350        2.41  Domestic  
42    37            86        2.97  Domestic  
10    44           425        2.28  Domestic  
21    46           318        2.47  Domestic  
18    43           250        2.56  Domestic  
27    41           302        2.47  Domestic  
53    36            97        3.70   Foreign  
71    35            89        3.78   Foreign

In [179]:
df4["price"]

0      4099
1      4749
2      3799
3      4816
4      7827
      ...  
69     7140
70     5397
71     4697
72     6850
73    11995
Name: price, Length: 74, dtype: int16

In [180]:
df4["price"].max()

15906

In [181]:
df4[df4["price"] == df4["price"].max()]

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
12  Cad. Seville  15906   21    3.0       3.0     13    4290     204    45   

    displacement  gear_ratio   foreign  
12           350        2.24  Domestic

In [182]:
df4[df4["price"] == df4["price"].min()]

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
33  Merc. Zephyr   3291   20    3.0       3.5     17    2830     195    43   

    displacement  gear_ratio   foreign  
33           140        3.08  Domestic

In [183]:
df4[df4["price"] == 15906]

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
12  Cad. Seville  15906   21    3.0       3.0     13    4290     204    45   

    displacement  gear_ratio   foreign  
12           350        2.24  Domestic

In [184]:
len(df4)

74

In [185]:
for i in range(len(df4)):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73


In [188]:
for i in range(len(df4)):
    preco = df4.iloc[i]['price']
    if preco == 15906:
        print(df4.iloc[i])
    else:
        continue # pass
        print("Jose")

make            Cad. Seville
price                  15906
mpg                       21
rep78                    3.0
headroom                 3.0
trunk                     13
weight                  4290
length                   204
turn                      45
displacement             350
gear_ratio              2.24
foreign             Domestic
Name: 12, dtype: object


In [189]:
for i in range(len(df4)):
    preco = df4.iloc[i]['price']
    if preco == 15906:
        print(df4.iloc[i])
    else:
        continue

make            Cad. Seville
price                  15906
mpg                       21
rep78                    3.0
headroom                 3.0
trunk                     13
weight                  4290
length                   204
turn                      45
displacement             350
gear_ratio              2.24
foreign             Domestic
Name: 12, dtype: object


In [190]:
df4.sort_values(by='price',ascending=False).tail(10)

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
19      Dodge Colt   3984   30    5.0       2.0      8    2120     163    35   
18      Chev. Nova   3955   19    3.0       3.5     13    3430     197    43   
64  Renault Le Car   3895   26    3.0       3.0     10    1830     142    34   
28    Merc. Bobcat   3829   22    4.0       3.0      9    2580     169    39   
2       AMC Spirit   3799   22    NaN       3.0     12    2640     168    35   
65          Subaru   3798   35    5.0       2.5     11    2050     164    36   
67  Toyota Corolla   3748   31    5.0       3.0      9    2200     165    35   
17     Chev. Monza   3667   24    2.0       2.0      7    2750     179    40   
13  Chev. Chevette   3299   29    3.0       2.5      9    2110     163    34   
33    Merc. Zephyr   3291   20    3.0       3.5     17    2830     195    43   

    displacement  gear_ratio   foreign  
19            98        3.54  Domestic  
18           250        2.56  Domestic  
64            79        3.72   Foreign  
28           140        2.73  Domestic  
2            121        3.08  Domestic  
65            97        3.81   Foreign  
67            97        3.21   Foreign  
17           151        2.73  Domestic  
13           231        2.93  Domestic  
33           140        3.08  Domestic

In [191]:
df_N3[0].sum()

2998533.948325042

In [192]:
print('Soma: ',         df4["price"].sum())
print('Valor máximo: ', df4["price"].max())
print('Valor mínimo: ', df4["price"].min())
print('Média',          df4["price"].mean())

Soma:  456229
Valor máximo:  15906
Valor mínimo:  3291
Média 6165.256756756757


Um outro comando bastante útil é o "value_counts". Com ele podemos contar a frequência de cada valor em um columa não numérica.

In [193]:
df4["foreign"].value_counts()

Domestic    52
Foreign     22
Name: foreign, dtype: int64

Pode-se, então, criar uma sub-base de dados baseada em valores específicos de uma coluna. Por exemplo, imagine que queremos apenas as informações dos carros importados.

In [194]:
carros_importados = df4[df4["foreign"] == 'Foreign']

In [93]:
carros_importados.to_stata("autos_importados.dta")

In [195]:
df4_impot = df4[df4["foreign"] == 'Foreign'] # Dados carros importados
df4_nacio = df4[df4["foreign"] == 'Domestic']

In [196]:
df4_impot.head()

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
52   Audi 5000   9690   17    5.0       3.0     15    2830     189    37   
53    Audi Fox   6295   23    3.0       2.5     11    2070     174    36   
54    BMW 320i   9735   25    4.0       2.5     12    2650     177    34   
55  Datsun 200   6229   23    4.0       1.5      6    2370     170    35   
56  Datsun 210   4589   35    5.0       2.0      8    2020     165    32   

    displacement  gear_ratio  foreign  
52           131        3.20  Foreign  
53            97        3.70  Foreign  
54           121        3.64  Foreign  
55           119        3.89  Foreign  
56            85        3.70  Foreign

In [197]:
df4_nacio.head()

make  price  mpg  rep78  headroom  trunk  weight  length  turn  \
0    AMC Concord   4099   22    3.0       2.5     11    2930     186    40   
1      AMC Pacer   4749   17    3.0       3.0     11    3350     173    40   
2     AMC Spirit   3799   22    NaN       3.0     12    2640     168    35   
3  Buick Century   4816   20    3.0       4.5     16    3250     196    40   
4  Buick Electra   7827   15    4.0       4.0     20    4080     222    43   

   displacement  gear_ratio   foreign  
0           121        3.58  Domestic  
1           258        2.53  Domestic  
2           121        3.08  Domestic  
3           196        2.93  Domestic  
4           350        2.41  Domestic

Vamos observar o preço médio do carro importado.

In [198]:
print('Média Impot.: ',df4_impot["price"].mean())
print('Média Nacio.: ',df4_nacio["price"].mean())

Média Impot.:  6384.681818181818
Média Nacio.:  6072.423076923077


In [199]:
df_filmes = pd.DataFrame(columns=('name', 'obs', 'rate'))

In [200]:
df_filmes

Empty DataFrame
Columns: [name, obs, rate]
Index: []

In [201]:
len(df_filmes)

0

In [202]:
df_filmes.loc[0] = ['Teste', '50', '4']

In [203]:
df_filmes

name obs rate
0  Teste  50    4

In [204]:
len(df_filmes)

1

In [205]:
df_filmes.loc[len(df_filmes)] = ['Rafaela', '50', '4']

In [206]:
df_filmes

name obs rate
0    Teste  50    4
1  Rafaela  50    4

In [207]:
len(df_filmes)

2

In [208]:
df_filmes

name obs rate
0    Teste  50    4
1  Rafaela  50    4

Deletar base de dados da memória

In [209]:
del(df_filmes)

In [210]:
df_filmes

NameError: name 'df_filmes' is not defined

In [211]:
df_filmes = pd.DataFrame(columns=('name', 'obs', 'rate'))

In [215]:
import requests
from bs4 import BeautifulSoup
import unicodedata
url = ['http://www.imdb.com/title/tt5013056/', 
       'http://www.imdb.com/title/tt1790809/',
       'http://www.imdb.com/title/tt1596346/',
       'http://www.imdb.com/title/tt0092099/',
       'http://www.imdb.com/title/tt0108052/']

In [216]:
headers = {
    "accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
    "accept-encoding": "gzip, deflate, br",
    "accept-language": "en-US,en;q=0.9",
    "sec-ch-ua": "'Not?A_Brand';v='8', 'Chromium';v='108', 'Google Chrome';v='108'",
    "sec-ch-ua-mobile": "?0",
    "sec-ch-ua-platform": "'macOS'",
    "sec-fetch-dest": "document",
    "sec-fetch-mode": "navigate",
    "sec-fetch-site": "none",
    "sec-fetch-user": "?1",
    "upgrade-insecure-requests": "1",
    "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36"}

In [213]:
def strip_accents(s):
    return ''.join(c for c in unicodedata.normalize('NFD', s) if unicodedata.category(c) != 'Mn')

In [214]:
df_filmes

Empty DataFrame
Columns: [name, obs, rate]
Index: []

In [217]:
for item in url:
    response = requests.get(item, headers=headers)
    soup = BeautifulSoup(response.text, 'lxml')
    name = strip_accents(soup.title.text)
    rate = soup.find_all("span", attrs={"class": "sc-bde20123-1 iZlgcd"})[0].text
    obs = soup.find_all("div", attrs={"class": "sc-bde20123-3 bjjENQ"})[0].text
    #print(name, obs, rate)
    df_filmes.loc[len(df_filmes)] = [name, obs, rate]

In [218]:
df_filmes

name   obs rate
0                              Dunkirk (2017) - IMDb  713K  7.8
1  Pirates of the Caribbean: Dead Men Tell No Tal...  333K  6.5
2                          Soul Surfer (2011) - IMDb   52K  7.0
3                              Top Gun (1986) - IMDb  485K  6.9
4                     Schindler's List (1993) - IMDb  1.4M  9.0

In [219]:
df_filmes.dtypes

name    object
obs     object
rate    object
dtype: object

Podemos observar o tipo de variável. No caso de rate, ela é um object. Ou seja, não numérica.

In [220]:
df_filmes["obs"].max()

'713K'

Neste caso, não conseguimos obter estatísticas

In [221]:
df_filmes["rate"].sum()

'7.86.57.06.99.0'

In [222]:
pd.to_numeric(df_filmes["rate"])

0    7.8
1    6.5
2    7.0
3    6.9
4    9.0
Name: rate, dtype: float64

Mas podemos converter: 

In [223]:
df_filmes["rate"] = pd.to_numeric(df_filmes["rate"])

In [224]:
df_filmes

name   obs  rate
0                              Dunkirk (2017) - IMDb  713K   7.8
1  Pirates of the Caribbean: Dead Men Tell No Tal...  333K   6.5
2                          Soul Surfer (2011) - IMDb   52K   7.0
3                              Top Gun (1986) - IMDb  485K   6.9
4                     Schindler's List (1993) - IMDb  1.4M   9.0

In [225]:
df_filmes["rate"]

0    7.8
1    6.5
2    7.0
3    6.9
4    9.0
Name: rate, dtype: float64

In [226]:
df_filmes["rate"].sum()

37.2

In [227]:
df_filmes.dtypes

name     object
obs      object
rate    float64
dtype: object

In [228]:
print(df_filmes["rate"].sum())
print(df_filmes["rate"].max())
print(df_filmes["rate"].min())
print(df_filmes["rate"].mean())

37.2
9.0
6.5
7.44


In [229]:
df_filmes

name   obs  rate
0                              Dunkirk (2017) - IMDb  713K   7.8
1  Pirates of the Caribbean: Dead Men Tell No Tal...  333K   6.5
2                          Soul Surfer (2011) - IMDb   52K   7.0
3                              Top Gun (1986) - IMDb  485K   6.9
4                     Schindler's List (1993) - IMDb  1.4M   9.0

In [230]:
df_filmes["obs"] = df_filmes["obs"].apply(lambda x: x.replace("K", "000").replace("M", "00000").replace(".", ""))

In [231]:
df_filmes

name      obs  rate
0                              Dunkirk (2017) - IMDb   713000   7.8
1  Pirates of the Caribbean: Dead Men Tell No Tal...   333000   6.5
2                          Soul Surfer (2011) - IMDb    52000   7.0
3                              Top Gun (1986) - IMDb   485000   6.9
4                     Schindler's List (1993) - IMDb  1400000   9.0

In [232]:
df_filmes["obs"] = pd.to_numeric(df_filmes["obs"])

In [233]:
df_filmes.dtypes

name     object
obs       int64
rate    float64
dtype: object

In [234]:
df_filmes

name      obs  rate
0                              Dunkirk (2017) - IMDb   713000   7.8
1  Pirates of the Caribbean: Dead Men Tell No Tal...   333000   6.5
2                          Soul Surfer (2011) - IMDb    52000   7.0
3                              Top Gun (1986) - IMDb   485000   6.9
4                     Schindler's List (1993) - IMDb  1400000   9.0

In [235]:
pd.get_dummies(df_filmes['name'], prefix="dum")

dum_Dunkirk (2017) - IMDb  \
0                          1   
1                          0   
2                          0   
3                          0   
4                          0   

   dum_Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb  \
0                                                  0                    
1                                                  1                    
2                                                  0                    
3                                                  0                    
4                                                  0                    

   dum_Schindler's List (1993) - IMDb  dum_Soul Surfer (2011) - IMDb  \
0                                   0                              0   
1                                   0                              0   
2                                   0                              1   
3                                   0                              0   
4                                   1                              0   

   dum_Top Gun (1986) - IMDb  
0                          0  
1                          0  
2                          0  
3                          1  
4                          0

Uma outra operação importante é obter dummies. Iremos criar uma outra base com a dummies e depois juntar a base original

In [236]:
df_dum = pd.get_dummies(df_filmes['name'])

In [237]:
df_dum

Dunkirk (2017) - IMDb  \
0                      1   
1                      0   
2                      0   
3                      0   
4                      0   

   Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb  \
0                                                  0                
1                                                  1                
2                                                  0                
3                                                  0                
4                                                  0                

   Schindler's List (1993) - IMDb  Soul Surfer (2011) - IMDb  \
0                               0                          0   
1                               0                          0   
2                               0                          1   
3                               0                          0   
4                               1                          0   

   Top Gun (1986) - IMDb  
0                      0  
1                      0  
2                      0  
3                      1  
4                      0

Podemos usar o comando ``pd.concat``para concatenar as duas bases

In [238]:
pd.concat([df_filmes, df_dum])

name        obs  rate  \
0                              Dunkirk (2017) - IMDb   713000.0   7.8   
1  Pirates of the Caribbean: Dead Men Tell No Tal...   333000.0   6.5   
2                          Soul Surfer (2011) - IMDb    52000.0   7.0   
3                              Top Gun (1986) - IMDb   485000.0   6.9   
4                     Schindler's List (1993) - IMDb  1400000.0   9.0   
0                                                NaN        NaN   NaN   
1                                                NaN        NaN   NaN   
2                                                NaN        NaN   NaN   
3                                                NaN        NaN   NaN   
4                                                NaN        NaN   NaN   

   Dunkirk (2017) - IMDb  \
0                    NaN   
1                    NaN   
2                    NaN   
3                    NaN   
4                    NaN   
0                    1.0   
1                    0.0   
2                    0.0   
3                    0.0   
4                    0.0   

   Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb  \
0                                                NaN                
1                                                NaN                
2                                                NaN                
3                                                NaN                
4                                                NaN                
0                                                0.0                
1                                                1.0                
2                                                0.0                
3                                                0.0                
4                                                0.0                

   Schindler's List (1993) - IMDb  Soul Surfer (2011) - IMDb  \
0                             NaN                        NaN   
1                             NaN                        NaN   
2                             NaN                        NaN   
3                             NaN                        NaN   
4                             NaN                        NaN   
0                             0.0                        0.0   
1                             0.0                        0.0   
2                             0.0                        1.0   
3                             0.0                        0.0   
4                             1.0                        0.0   

   Top Gun (1986) - IMDb  
0                    NaN  
1                    NaN  
2                    NaN  
3                    NaN  
4                    NaN  
0                    0.0  
1                    0.0  
2                    0.0  
3                    1.0  
4                    0.0

In [239]:
df_filmes = pd.concat([df_filmes, df_dum], axis=1)

In [240]:
df_filmes

name      obs  rate  \
0                              Dunkirk (2017) - IMDb   713000   7.8   
1  Pirates of the Caribbean: Dead Men Tell No Tal...   333000   6.5   
2                          Soul Surfer (2011) - IMDb    52000   7.0   
3                              Top Gun (1986) - IMDb   485000   6.9   
4                     Schindler's List (1993) - IMDb  1400000   9.0   

   Dunkirk (2017) - IMDb  \
0                      1   
1                      0   
2                      0   
3                      0   
4                      0   

   Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb  \
0                                                  0                
1                                                  1                
2                                                  0                
3                                                  0                
4                                                  0                

   Schindler's List (1993) - IMDb  Soul Surfer (2011) - IMDb  \
0                               0                          0   
1                               0                          0   
2                               0                          1   
3                               0                          0   
4                               1                          0   

   Top Gun (1986) - IMDb  
0                      0  
1                      0  
2                      0  
3                      1  
4                      0

In [242]:
df_filmes.style.to_latex()

"\\begin{tabular}{llrrrrrrr}\n & name & obs & rate & Dunkirk (2017) - IMDb & Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb & Schindler's List (1993) - IMDb & Soul Surfer (2011) - IMDb & Top Gun (1986) - IMDb \\\\\n0 & Dunkirk (2017) - IMDb & 713000 & 7.800000 & 1 & 0 & 0 & 0 & 0 \\\\\n1 & Pirates of the Caribbean: Dead Men Tell No Tales (2017) - IMDb & 333000 & 6.500000 & 0 & 1 & 0 & 0 & 0 \\\\\n2 & Soul Surfer (2011) - IMDb & 52000 & 7.000000 & 0 & 0 & 0 & 1 & 0 \\\\\n3 & Top Gun (1986) - IMDb & 485000 & 6.900000 & 0 & 0 & 0 & 0 & 1 \\\\\n4 & Schindler's List (1993) - IMDb & 1400000 & 9.000000 & 0 & 0 & 1 & 0 & 0 \\\\\n\\end{tabular}\n"

In [1]:
import pandas as pd
import pickle

In [3]:
df = pd.read_pickle('dados.pkl')

## Infrações IBAMA

In [251]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import multiprocessing as mp 
from joblib import Parallel, delayed
import time

In [252]:
num_cores = mp.cpu_count()

In [253]:
num_cores

8

In [254]:
from requests.adapters import HTTPAdapter
from urllib3.util.retry import Retry


session = requests.Session()
retry = Retry(connect=3, backoff_factor=0.5)
adapter = HTTPAdapter(max_retries=retry)
session.mount('http://', adapter)
session.mount('https://', adapter)

In [247]:
r = session.get("http://dadosabertos.ibama.gov.br/dados/SIFISC/auto_infracao/auto_infracao/auto_infracao.html", verify=False)

/opt/miniconda3/lib/python3.9/site-packages/urllib3/connectionpool.py:1045: InsecureRequestWarning: Unverified HTTPS request is being made to host 'dadosabertos.ibama.gov.br'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/1.26.x/advanced-usage.html#ssl-warnings
  warnings.warn(


In [248]:
texto = r.text

In [260]:
texto[0:2000]

'<html><body><h1>AUTO DE INFRAÇÃO <br>Atualizado em: 01/10/2023 6:35</h1><table border="1" cellspacing="1" cellpadding="5"><thead bgcolor="#808080"><th align="center">SEQ AUTO INFRACAO</th><th align="center">NUM_AUTO_INFRACAO</th><th align="center">SER_AUTO_INFRACAO</th><th align="center">TIPO_AUTO</th><th align="center">TIPO_MULTA</th><th align="center">VAL_AUTO_INFRACAO</th><th align="center">PATRIMONIO_APURACAO</th><th align="center">PATRIMONIO_PORTE</th><th align="center">GRAVIDADE_INFRACAO</th><th align="center">UNID_ARRECADACAO</th><th align="center">DES_AUTO_INFRACAO</th><th align="center">DAT_HORA_AUTO_INFRACAO</th><th align="center">FORMA_ENTREGA</th><th align="center">DAT_CIENCIA_AUTUACAO</th><th align="center">COD_MUNICIPIO</th><th align="center">MUNICIPIO</th><th align="center">UF</th><th align="center">NUM_PROCESSO</th><th align="center">COD_INFRACAO</th><th align="center">DES_INFRACAO</th><th align="center">TIPO_INFRACAO</th><th align="center">NOME_INFRATOR</th><th align=

In [256]:
texto[-1000:]

'<td></td><td>multa simples;</td><td>Fechada</td><td>5000.0</td><td></td><td></td><td></td><td></td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>05/08/2022 17:46:40</td><td>Representante</td><td></td><td>4118709</td><td>Paulo Frontin</td><td>PR</td><td>02017.002161/2022-06</td><td>272491.0</td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>Flora</td><td>Eliane Sfair dos Santos</td><td>01834887925</td><td></td><td>Atividade</td><td></td><td></td><td>-26,17136111111111</td><td>-50,73886111111111</td><td>Fazenda Chapéu de Sol</td><td></td><td></td><td>SUPES/PR</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>05/08/2022 17:51:56</td><td></td></tr></tbody></table></body></html

In [261]:
texto_0 = texto.split("</thead><tbody>")[0]
colunas = [item.text for item in BeautifulSoup(texto_0.split('<thead bgcolor="#808080">')[1],'lxml').find_all('th')]

In [262]:
colunas

['SEQ AUTO INFRACAO',
 'NUM_AUTO_INFRACAO',
 'SER_AUTO_INFRACAO',
 'TIPO_AUTO',
 'TIPO_MULTA',
 'VAL_AUTO_INFRACAO',
 'PATRIMONIO_APURACAO',
 'PATRIMONIO_PORTE',
 'GRAVIDADE_INFRACAO',
 'UNID_ARRECADACAO',
 'DES_AUTO_INFRACAO',
 'DAT_HORA_AUTO_INFRACAO',
 'FORMA_ENTREGA',
 'DAT_CIENCIA_AUTUACAO',
 'COD_MUNICIPIO',
 'MUNICIPIO',
 'UF',
 'NUM_PROCESSO',
 'COD_INFRACAO',
 'DES_INFRACAO',
 'TIPO_INFRACAO',
 'NOME_INFRATOR',
 'CPF_CNPJ_INFRATOR',
 'QTD_AREA',
 'INFRACAO_AREA',
 'DES_OUTROS_TIPO_AREA',
 'CLASSIFICACAO_AREA',
 'NUM_LATITUDE_AUTO',
 'NUM_LONGITUDE_AUTO',
 'DES_LOCAL_INFRACAO',
 'NOTIFICACAO_VINCULADA',
 'ACAO_FISCALIZATORIA',
 'UNID_CONTROLE',
 'TIPO_ACAO',
 'OPERACAO',
 'DENUNCIA_SISLIV',
 'ORDEM_FISCALIZACAO',
 'SOLICITACAO_RECURSO',
 'OPERACAO_SOL_RECURSO',
 'DAT_LANCAMENTO',
 'DAT_ULT_ALTERACAO',
 'TIPO_ULT_ALTERACAO']

In [263]:
texto_1 = texto.split("</thead><tbody>")[1]
texto_final = texto_1.split("</tbody></table>")[0]

In [264]:
texto_final[0:1000]

'<tr><td>3.0</td><td>26363</td><td>D</td><td>Multa simples</td><td></td><td>1500.0</td><td></td><td></td><td></td><td>IMP/GEREX</td><td>POR FUNCIONAR ESTABELICIMENTO PONTENCIALMENTE POLUIDORAS SEM O CADASTRO TECNICO FEDERAL SEM APRESENTAR RELATORIO ANUAL DE SUAS ATIVIDEDAS</td><td>05/03/2004 00:00:00</td><td></td><td>05/03/2004</td><td>2105302</td><td>IMPERATRIZ</td><td>MA</td><td>0205100001204</td><td>401001.0</td><td>Funcionar sem prévio registro no Ibama - Administradora</td><td>Penalidade pecuniária - Flora</td><td>PALADAR IOGURTE LTDA</td><td>01790868000103</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>-</td><td></td><td>IMP/GEREX</td><td>Rotina</td><td></td><td>/</td><td></td><td></td><td></td><td>01/06/2004 10:13:30</td><td>06/09/2010 10:09:03</td><td>Preenchido</td></tr><tr><td>4.0</td><td>26364</td><td>D</td><td>Multa simples</td><td></td><td>1500.0</td><td></td><td></td><td></td><td>IMP/GEREX</td><td>POR FUCIONAR ESTABELECIMENTO POTENCIALMENTE POLUIDO

In [265]:
texto_final[-1000:]

'<tr><td></td><td>ZZX3XEZJ</td><td></td><td>multa simples;</td><td>Fechada</td><td>5000.0</td><td></td><td></td><td></td><td></td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>05/08/2022 17:46:40</td><td>Representante</td><td></td><td>4118709</td><td>Paulo Frontin</td><td>PR</td><td>02017.002161/2022-06</td><td>272491.0</td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>Flora</td><td>Eliane Sfair dos Santos</td><td>01834887925</td><td></td><td>Atividade</td><td></td><td></td><td>-26,17136111111111</td><td>-50,73886111111111</td><td>Fazenda Chapéu de Sol</td><td></td><td></td><td>SUPES/PR</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>05/08/2022 17:51:56</td><td></td></tr

In [266]:
texto_completo = texto_final.split("<tr>")

In [267]:
len(texto_completo)

659542

In [268]:
texto_completo[0]

''

In [269]:
texto_completo[1]

'<td>3.0</td><td>26363</td><td>D</td><td>Multa simples</td><td></td><td>1500.0</td><td></td><td></td><td></td><td>IMP/GEREX</td><td>POR FUNCIONAR ESTABELICIMENTO PONTENCIALMENTE POLUIDORAS SEM O CADASTRO TECNICO FEDERAL SEM APRESENTAR RELATORIO ANUAL DE SUAS ATIVIDEDAS</td><td>05/03/2004 00:00:00</td><td></td><td>05/03/2004</td><td>2105302</td><td>IMPERATRIZ</td><td>MA</td><td>0205100001204</td><td>401001.0</td><td>Funcionar sem prévio registro no Ibama - Administradora</td><td>Penalidade pecuniária - Flora</td><td>PALADAR IOGURTE LTDA</td><td>01790868000103</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>-</td><td></td><td>IMP/GEREX</td><td>Rotina</td><td></td><td>/</td><td></td><td></td><td></td><td>01/06/2004 10:13:30</td><td>06/09/2010 10:09:03</td><td>Preenchido</td></tr>'

In [270]:
texto_completo[-1]

'<td></td><td>ZZX3XEZJ</td><td></td><td>multa simples;</td><td>Fechada</td><td>5000.0</td><td></td><td></td><td></td><td></td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>05/08/2022 17:46:40</td><td>Representante</td><td></td><td>4118709</td><td>Paulo Frontin</td><td>PR</td><td>02017.002161/2022-06</td><td>272491.0</td><td>Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.</td><td>Flora</td><td>Eliane Sfair dos Santos</td><td>01834887925</td><td></td><td>Atividade</td><td></td><td></td><td>-26,17136111111111</td><td>-50,73886111111111</td><td>Fazenda Chapéu de Sol</td><td></td><td></td><td>SUPES/PR</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>05/08/2022 17:51:56</td><td></td></tr>'

In [271]:
texto_completo = texto_completo[1:]
tc = ["<tr>"+text for text in texto_completo]

In [272]:
tc[0]

'<tr><td>3.0</td><td>26363</td><td>D</td><td>Multa simples</td><td></td><td>1500.0</td><td></td><td></td><td></td><td>IMP/GEREX</td><td>POR FUNCIONAR ESTABELICIMENTO PONTENCIALMENTE POLUIDORAS SEM O CADASTRO TECNICO FEDERAL SEM APRESENTAR RELATORIO ANUAL DE SUAS ATIVIDEDAS</td><td>05/03/2004 00:00:00</td><td></td><td>05/03/2004</td><td>2105302</td><td>IMPERATRIZ</td><td>MA</td><td>0205100001204</td><td>401001.0</td><td>Funcionar sem prévio registro no Ibama - Administradora</td><td>Penalidade pecuniária - Flora</td><td>PALADAR IOGURTE LTDA</td><td>01790868000103</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>-</td><td></td><td>IMP/GEREX</td><td>Rotina</td><td></td><td>/</td><td></td><td></td><td></td><td>01/06/2004 10:13:30</td><td>06/09/2010 10:09:03</td><td>Preenchido</td></tr>'

In [273]:
len(tc)

659541

In [274]:
def gustavo(item):
	data = {}
	item_soup = BeautifulSoup(item,'lxml')
	tds = item_soup.find_all("td")
	dados = [i.text for i in tds]
	for i,j in zip(colunas,dados):
		data[i] = j
	return data

In [275]:
gustavo(tc[0])

{'SEQ AUTO INFRACAO': '3.0',
 'NUM_AUTO_INFRACAO': '26363',
 'SER_AUTO_INFRACAO': 'D',
 'TIPO_AUTO': 'Multa simples',
 'TIPO_MULTA': '',
 'VAL_AUTO_INFRACAO': '1500.0',
 'PATRIMONIO_APURACAO': '',
 'PATRIMONIO_PORTE': '',
 'GRAVIDADE_INFRACAO': '',
 'UNID_ARRECADACAO': 'IMP/GEREX',
 'DES_AUTO_INFRACAO': 'POR FUNCIONAR ESTABELICIMENTO PONTENCIALMENTE POLUIDORAS SEM O CADASTRO TECNICO FEDERAL SEM APRESENTAR RELATORIO ANUAL DE SUAS ATIVIDEDAS',
 'DAT_HORA_AUTO_INFRACAO': '05/03/2004 00:00:00',
 'FORMA_ENTREGA': '',
 'DAT_CIENCIA_AUTUACAO': '05/03/2004',
 'COD_MUNICIPIO': '2105302',
 'MUNICIPIO': 'IMPERATRIZ',
 'UF': 'MA',
 'NUM_PROCESSO': '0205100001204',
 'COD_INFRACAO': '401001.0',
 'DES_INFRACAO': 'Funcionar sem prévio registro no Ibama - Administradora',
 'TIPO_INFRACAO': 'Penalidade pecuniária - Flora',
 'NOME_INFRATOR': 'PALADAR IOGURTE LTDA',
 'CPF_CNPJ_INFRATOR': '01790868000103',
 'QTD_AREA': '',
 'INFRACAO_AREA': '',
 'DES_OUTROS_TIPO_AREA': '',
 'CLASSIFICACAO_AREA': '',
 'NUM_

In [276]:
gustavo(tc[-1])

{'SEQ AUTO INFRACAO': '',
 'NUM_AUTO_INFRACAO': 'ZZX3XEZJ',
 'SER_AUTO_INFRACAO': '',
 'TIPO_AUTO': 'multa simples;',
 'TIPO_MULTA': 'Fechada',
 'VAL_AUTO_INFRACAO': '5000.0',
 'PATRIMONIO_APURACAO': '',
 'PATRIMONIO_PORTE': '',
 'GRAVIDADE_INFRACAO': '',
 'UNID_ARRECADACAO': '',
 'DES_AUTO_INFRACAO': 'Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.',
 'DAT_HORA_AUTO_INFRACAO': '05/08/2022 17:46:40',
 'FORMA_ENTREGA': 'Representante',
 'DAT_CIENCIA_AUTUACAO': '',
 'COD_MUNICIPIO': '4118709',
 'MUNICIPIO': 'Paulo Frontin',
 'UF': 'PR',
 'NUM_PROCESSO': '02017.002161/2022-06',
 'COD_INFRACAO': '272491.0',
 'DES_INFRACAO': 'Impedir a regeneração natural de floresta nativa, por meio de atividade de agricultura, em uma área de 01 ha (um hectare), sendo esta parte da área embargada sob o termo de n. 835/E.',
 'TIPO_INFRACAO': 'Flora',
 'NOME_INFRATOR': 'Elian

In [277]:
%time
dados_final = Parallel(n_jobs=num_cores)(delayed(gustavo)(i) for i in tc)

CPU times: user 4 µs, sys: 2 µs, total: 6 µs
Wall time: 10 µs


In [278]:
len(dados_final)

659541

In [279]:
dados_final[0]

{'SEQ AUTO INFRACAO': '3.0',
 'NUM_AUTO_INFRACAO': '26363',
 'SER_AUTO_INFRACAO': 'D',
 'TIPO_AUTO': 'Multa simples',
 'TIPO_MULTA': '',
 'VAL_AUTO_INFRACAO': '1500.0',
 'PATRIMONIO_APURACAO': '',
 'PATRIMONIO_PORTE': '',
 'GRAVIDADE_INFRACAO': '',
 'UNID_ARRECADACAO': 'IMP/GEREX',
 'DES_AUTO_INFRACAO': 'POR FUNCIONAR ESTABELICIMENTO PONTENCIALMENTE POLUIDORAS SEM O CADASTRO TECNICO FEDERAL SEM APRESENTAR RELATORIO ANUAL DE SUAS ATIVIDEDAS',
 'DAT_HORA_AUTO_INFRACAO': '05/03/2004 00:00:00',
 'FORMA_ENTREGA': '',
 'DAT_CIENCIA_AUTUACAO': '05/03/2004',
 'COD_MUNICIPIO': '2105302',
 'MUNICIPIO': 'IMPERATRIZ',
 'UF': 'MA',
 'NUM_PROCESSO': '0205100001204',
 'COD_INFRACAO': '401001.0',
 'DES_INFRACAO': 'Funcionar sem prévio registro no Ibama - Administradora',
 'TIPO_INFRACAO': 'Penalidade pecuniária - Flora',
 'NOME_INFRATOR': 'PALADAR IOGURTE LTDA',
 'CPF_CNPJ_INFRATOR': '01790868000103',
 'QTD_AREA': '',
 'INFRACAO_AREA': '',
 'DES_OUTROS_TIPO_AREA': '',
 'CLASSIFICACAO_AREA': '',
 'NUM_

In [280]:
df = pd.DataFrame(dados_final)

In [281]:
df

SEQ AUTO INFRACAO NUM_AUTO_INFRACAO SER_AUTO_INFRACAO       TIPO_AUTO  \
0                    3.0             26363                 D   Multa simples   
1                    4.0             26364                 D   Multa simples   
2                    5.0             26365                 D   Multa simples   
3                    7.0             26367                 D   Multa simples   
4                    9.0             26369                 D   Multa simples   
...                  ...               ...               ...             ...   
659536                            ZZKWIRGS                    multa simples;   
659537                            ZZM64AB4                    multa simples;   
659538                            ZZM64AB4                    multa simples;   
659539                            ZZORTR3Q                    multa simples;   
659540                            ZZX3XEZJ                    multa simples;   

       TIPO_MULTA VAL_AUTO_INFRACAO PATRIMONIO_APURACAO PATRIMONIO_PORTE  \
0                            1500.0                                        
1                            1500.0                                        
2                            2500.0                                        
3                             200.0                                        
4                             600.0                                        
...           ...               ...                 ...              ...   
659536    Fechada         2707500.0                                        
659537     Aberta          325000.0                                        
659538     Aberta          325000.0                                        
659539     Aberta            4200.0                                        
659540    Fechada            5000.0                                        

       GRAVIDADE_INFRACAO UNID_ARRECADACAO  ... UNID_CONTROLE TIPO_ACAO  \
0                                IMP/GEREX  ...     IMP/GEREX    Rotina   
1                                IMP/GEREX  ...     IMP/GEREX             
2                                IMP/GEREX  ...     IMP/GEREX             
3                                IMP/GEREX  ...     IMP/GEREX             
4                                IMP/GEREX  ...     IMP/GEREX             
...                   ...              ...  ...           ...       ...   
659536                                      ...      DITEC/PA             
659537               Mdio                   ...      DITEC/MA             
659538               Mdio                   ...      DITEC/MA             
659539               Mdio                   ...        ICMBio             
659540                                      ...      SUPES/PR             

       OPERACAO DENUNCIA_SISLIV ORDEM_FISCALIZACAO SOLICITACAO_RECURSO  \
0                             /                                          
1                             /                                          
2                             /                                          
3                             /                                          
4                             /                                          
...         ...             ...                ...                 ...   
659536                                                                   
659537                                                                   
659538                                                                   
659539                                                                   
659540                                                                   

       OPERACAO_SOL_RECURSO       DAT_LANCAMENTO    DAT_ULT_ALTERACAO  \
0                            01/06/2004 10:13:30  06/09/2010 10:09:03   
1                            01/06/2004 10:01:11  01/06/2004 10:01:11   
2                            12/07/2004 11:58:19  12/07/2004 11:58:19   
3                            07/10/2005 17:14:21  2

In [282]:
df['VAL_AUTO_INFRACAO'] = df['VAL_AUTO_INFRACAO'].apply(lambda x: x.replace(",","."))

In [283]:
df['VAL_AUTO_INFRACAO'] = pd.to_numeric(df['VAL_AUTO_INFRACAO'])

In [284]:
df['VAL_AUTO_INFRACAO']

0            1500.0
1            1500.0
2            2500.0
3             200.0
4             600.0
            ...    
659536    2707500.0
659537     325000.0
659538     325000.0
659539       4200.0
659540       5000.0
Name: VAL_AUTO_INFRACAO, Length: 659541, dtype: float64

In [285]:
df['VAL_AUTO_INFRACAO'].max()

4306569666.0

In [286]:
df[df['VAL_AUTO_INFRACAO'] == df['VAL_AUTO_INFRACAO'].max()]

SEQ AUTO INFRACAO NUM_AUTO_INFRACAO SER_AUTO_INFRACAO      TIPO_AUTO  \
235761          748345.0            285378                 A  Multa simples   

       TIPO_MULTA  VAL_AUTO_INFRACAO PATRIMONIO_APURACAO PATRIMONIO_PORTE  \
235761                  4.306570e+09                                        

       GRAVIDADE_INFRACAO UNID_ARRECADACAO  ... UNID_CONTROLE TIPO_ACAO  \
235761                          CONV/PM/MG  ...      MG/SUPES             

       OPERACAO DENUNCIA_SISLIV ORDEM_FISCALIZACAO SOLICITACAO_RECURSO  \
235761                        /                                          

       OPERACAO_SOL_RECURSO       DAT_LANCAMENTO    DAT_ULT_ALTERACAO  \
235761                       02/02/2005 15:40:10  02/02/2005 15:40:10   

       TIPO_ULT_ALTERACAO  
235761         Preenchido  

[1 rows x 42 columns]

In [288]:
df.iloc[235761]

SEQ AUTO INFRACAO                                                  748345.0
NUM_AUTO_INFRACAO                                                    285378
SER_AUTO_INFRACAO                                                         A
TIPO_AUTO                                                     Multa simples
TIPO_MULTA                                                                 
VAL_AUTO_INFRACAO                                              4306569666.0
PATRIMONIO_APURACAO                                                        
PATRIMONIO_PORTE                                                           
GRAVIDADE_INFRACAO                                                         
UNID_ARRECADACAO                                                 CONV/PM/MG
DES_AUTO_INFRACAO         POR CONSUMIR QUANTIDADE SUPERIOR DE MDC AO PRE...
DAT_HORA_AUTO_INFRACAO                                  28/08/1992 00:00:00
FORMA_ENTREGA                                                              
DAT_CIENCIA_

In [289]:
df.iloc[235761]['DES_AUTO_INFRACAO']

'POR CONSUMIR QUANTIDADE SUPERIOR DE MDC AO PREVISTO NO PIFI.'

In [290]:
df[df['VAL_AUTO_INFRACAO'] >= 30000000]

SEQ AUTO INFRACAO NUM_AUTO_INFRACAO SER_AUTO_INFRACAO       TIPO_AUTO  \
14698            18168.0             71081                 B   Multa simples   
24303            28280.0            526862                 D   Multa simples   
24304            28285.0            526867                 D   Multa simples   
34987            61634.0            509919                 D   Multa simples   
54226           424698.0            111655                 A   Multa simples   
...                  ...               ...               ...             ...   
653919                            OPY26H1C                    multa simples;   
654487                            PV9M7H24                    multa simples;   
654694                            QATIH3TI                    multa simples;   
654857                            QM5CV1O9                    multa simples;   
658414                            XTV64M5P                    multa simples;   

       TIPO_MULTA  VAL_AUTO_INFRACAO PATRIMONIO_APURACAO PATRIMONIO_PORTE  \
14698                    200000000.0                                        
24303                    147621215.0                                        
24304                     38755143.0                                        
34987                     50000000.0                                        
54226                    149182200.0                                        
...           ...                ...                 ...              ...   
653919    Fechada         50000000.0                                        
654487     Aberta         35055000.0                                        
654694    Fechada         31338300.0                                        
654857     Aberta         35055000.0                                        
658414    Fechada         43640000.0                                        

       GRAVIDADE_INFRACAO UNID_ARRECADACAO  ...      UNID_CONTROLE TIPO_ACAO  \
14698                           CONV/PM/MG  ...           MG/SUPES             
24303                             DF/SUPES  ...           DF/SUPES             
24304                             DF/SUPES  ...           DF/SUPES             
34987                             RJ/SUPES  ...           RJ/SUPES             
54226                              DES3453  ...                                
...                   ...              ...  ...                ...       ...   
653919                                      ...           NUBIO/SC             
654487               Mdio                   ...  UNID_TEC_OIAPOQUE             
654694                                      ...              COFIS             
654857               Mdio                   ...  UNID_TEC_OIAPOQUE             
658414                                      ...             ICMBio             

       OPERACAO DENUNCIA_SISLIV ORDEM_FISCALIZACAO SOLICITACAO_RECURSO  \
14698                         /                                          
24303                         /                                          
24304                         /                                          
34987                         /                                          
54226                         /                                          
...         ...             ...                ...                 ...   
653919                                                                   
654487                                                                   
654694                                                                   
654857                                                                   
658414                                                                   

       OPERACAO_SOL_RECURSO       DAT_LANCAMENTO    DAT_ULT_ALTERACAO  \
14698                        07/12/1998 00:00:00  07/12/1998 00:00:00   
24303                        31/10/2005 14:36:44  27/03/2006 14:39:51   
24304                        31/10/2005 14:36:44  27

In [175]:
df.to_pickle("ibama_infracao_OUT_2022.pkl")

In [286]:
df.iloc[10]

SEQ AUTO INFRACAO                                                      19,0
NUM_AUTO_INFRACAO                                                     26379
SER_AUTO_INFRACAO                                                         D
TIPO_AUTO                                                     Multa simples
TIPO_MULTA                                                                 
VAL_AUTO_INFRACAO                                                     300.0
PATRIMONIO_APURACAO                                                        
PATRIMONIO_PORTE                                                           
GRAVIDADE_INFRACAO                                                         
UNID_ARRECADACAO                                                  IMP/GEREX
DES_AUTO_INFRACAO         POR COMERCIALIZAR PRODUTO  FLORESTAIS  A SABER...
DAT_HORA_AUTO_INFRACAO                                  13/04/2005 10:20:00
FORMA_ENTREGA                                                              
DAT_CIENCIA_

In [287]:
df.iloc[10]['DES_AUTO_INFRACAO']

'POR COMERCIALIZAR PRODUTO  FLORESTAIS  A SABER: 2,816 M3 DE MADEIRA EM TOROS DA ESSÊNCIA FLORESTAL JATOBÁ, SEM ADEVIDA COBERTURA DE ATPF.'

In [288]:
df.iloc[10000]

SEQ AUTO INFRACAO                                                   12459,0
NUM_AUTO_INFRACAO                                                     26551
SER_AUTO_INFRACAO                                                         D
TIPO_AUTO                                                     Multa simples
TIPO_MULTA                                                                 
VAL_AUTO_INFRACAO                                                    4300.0
PATRIMONIO_APURACAO                                                        
PATRIMONIO_PORTE                                                           
GRAVIDADE_INFRACAO                                                         
UNID_ARRECADACAO                                                   MA/SUPES
DES_AUTO_INFRACAO         TRANSPORTAR 42 M3 DE CARVÃO VEGETAL SEM CARIMB...
DAT_HORA_AUTO_INFRACAO                                  03/11/2000 00:00:00
FORMA_ENTREGA                                                              
DAT_CIENCIA_

In [289]:
df.iloc[10000]['DES_AUTO_INFRACAO']

'TRANSPORTAR 42 M3 DE CARVÃO VEGETAL SEM CARIMBO VALIDO EM BRANCO  CAMPO 19 ATPF  Nº0547259 CAMINHÃO MERCEDES BENZ BRANCA PLACA HPF 3238 -MA LAT.05.39.05 S LONG. 49.29.3 S'