# Aula 4: Inserção em bases de dados relacionais

Um banco de dados relacional é um banco de dados que modela os dados de uma forma que eles sejam percebidos pelo usuário como tabelas, ou mais formalmente relações.

### SQL

``
conda install mysql-connector-python
``

Vamos agora nos concentrar em SQL. Utilizaremos aqui a versão free MySQL. Existem outras bases relacionais como ORACLE, MSSQL, POSTGRES, ...

#### LISTAR BASES DE DADOS
``SHOW DATABASES;
``

#### CRIAR BASE DE DADOS SQL
``CREATE DATABASE aula;
 USE aula;``

#### LISTAR TABELAS
``SHOW tables;
``

#### CREATE TABLE IN DATABASE
``
 CREATE TABLE filmes (name, rate INT, obs);
 CREATE TABLE filmes (name TEXT NOT NULL, rate TEXT NOT NULL, obs TEXT NOT NULL);
 SELECT * FROM filmes;
 INSERT INTO filmes SET name = 'Gustavo', rate = '1000', obs = '1';
 INSERT INTO filmes (name, rate, obs) values ('UFPE', '100', '2');
 SELECT * FROM filmes;``
 
#### APAGAR TABELA
``DROP table filmes;
``
#### APAGAR BASE DE DADOS
``DROP DATABASE aula;
``

Inicialmente, já que sabemos definir funções, podemos criar uma função para um INSERT em uma bas de dados

In [15]:
def insert(table, data):
    '''O campo data é um dicionário '''
    query = "INSERT INTO " + table + " SET "
    combined = []
    for field in data:
        if(field):
            combined.append("%s = '%s'" % (field, data[field]))
    query += ", ".join(combined)
    print(query)

In [16]:
insert('filmes', {"name":"Gustavo","rate":"1000","obs":"1"})

INSERT INTO filmes SET name = 'Gustavo', rate = '1000', obs = '1'


In [17]:
rate = 20

In [19]:
rate

20

In [20]:
print(rate)

20


In [24]:
print("%s" % rate)

20


In [28]:
"INSERT INTO " + 'filmes' + " SET "

'INSERT INTO filmes SET '

In [32]:
data = {"name":"Gustavo","rate":"1000","obs":"1"}

In [33]:
data["name"]

'Gustavo'

In [34]:
for i in data:
    print(i, data[i])

name Gustavo
rate 1000
obs 1


In [36]:
data = {"name":"Gustavo","rate":"1000","obs":"1"}
for i in data:
    print(i,data[i])

name Gustavo
rate 1000
obs 1


In [38]:
data[i]

'1'

In [30]:
"%s = '%s'" % (i, data[i])

"obs = '1'"

In [112]:
data = {"name":"Gustavo","rate":"1000","obs":"1"}

In [114]:
data['name']

'Gustavo'

In [35]:
"%s = '%s'" % ('name', data['name'])

"name = 'Gustavo'"

In [44]:
query = "INSERT INTO " + 'filmes' + " SET "
query

'INSERT INTO filmes SET '

In [39]:
combined = []

In [40]:
for field in {"name":"Gustavo","rate":"1000","obs":"1"}:
    combined.append("%s = '%s'" % (field, data[field]))

In [41]:
combined

["name = 'Gustavo'", "rate = '1000'", "obs = '1'"]

In [42]:
", ".join(combined)

"name = 'Gustavo', rate = '1000', obs = '1'"

In [45]:
query += ", ".join(combined)

In [46]:
query

"INSERT INTO filmes SET name = 'Gustavo', rate = '1000', obs = '1'"

NameError: name 'query' is not defined

Para realizarmos uma inserção de dados ou a leitura de dados de uma tabela em SQL, precisaremos criar uma conexão a partir do pyhon para a base de dados.

Faremos isto importando o conector mysql

In [8]:
import os
import mysql.connector as mdb

e criando a conexão e o cursor que fará toda a execução de operação

In [12]:
con = mdb.connect(user='gsampaio', host='localhost', password ='gsampaio1982', database='aula')

In [13]:
con

In [14]:
cursor = con.cursor()

In [26]:
cursor

In [23]:
cursor.execute("select * from filmes")

In [24]:
cursor.fetchall()

[('Gustavo', '1000', '1'),
 ('UFPE', '100', '2'),
 ('Pedro', '100', '3'),
 ('Sofia', '10000', '5'),
 ('Dunkirk (2017) - IMDb', '7.8', '648K'),
 ('Piratas do Caribe: A Vingança de Salazar (2017) - IMDb', '6.5', '309K'),
 ('Soul Surfer: Coragem de Viver (2011) - IMDb', '7.0', '50K'),
 ('Top Gun: Ases Indomáveis (1986) - IMDb', '6.9', '423K'),
 ('A Lista de Schindler (1993) - IMDb', '9.0', '1.3M'),
 ('Gustavo Sampaio TESTE', '877767', '5')]

Podemos utilizar o cursos para executar qualquer comando em SQL. Por exemplo, vamos executar o INSERT anterior

Após a execução precisaremos *commit* a execução e podemos fechar a conexão e o cursor.

In [29]:
cursor.execute("INSERT INTO filmes SET name = 'Gustavo Sampaio TESTE', rate = '877767', obs = '5'")

In [30]:
con.commit()

In [8]:
cursor.close()
con.close()

Vamos modificar ligeiramente nossa função [insert]() definida acima. Iremos trocar o print pela execução do cursor.

In [25]:
def insert(table, data):
    query = "INSERT INTO " + table + " SET "
    combined = []
    for field in data:
        if(field):
            combined.append("%s = '%s'" % (field, data[field]))
    query += ", ".join(combined)
    cursor.execute(query)

In [ ]:
con=mdb.connect(user='user', password ='passwd', database='aula')
cursor = con.cursor();

In [55]:
import requests
from bs4 import BeautifulSoup
url = ['http://www.imdb.com/title/tt5013056/', 'http://www.imdb.com/title/tt1790809/',
       'http://www.imdb.com/title/tt1596346/','http://www.imdb.com/title/tt0092099/',
       'http://www.imdb.com/title/tt0108052/']

In [58]:
for item in url:
    fields = {}
    response = requests.get(item)
    soup = BeautifulSoup(response.text, 'lxml')
    name = soup.title.text
    rate = soup.find_all("span", attrs={"class": "sc-bde20123-1 iZlgcd"})[0].text
    obs = soup.find_all("div", attrs={"class": "sc-bde20123-3 bjjENQ"})[0].text
    try:
        obs1 = soup.find_all("div", "imdbRatinggggg")[0].a.text
    except:
        obs1 = '-'
    fields["name"] = name.replace("'", "")
    fields["rate"] = rate.replace("'", "")
    fields["obs"] = obs.replace("'", "")
    insert('filmes', fields)
    #insertstmt=("INSERT INTO filmes (name, rate, obs) values ('%s', '%s', '%s')" % (name, rate, obs))
    #cursor.execute(insertstmt)
    #print(insertstmt)
    print(fields)
    #print ('%s\t,%s\t,%s\t,%s\n' % (name,obs,obs1,rate))

{'name': 'Dunkirk (2017) - IMDb', 'rate': '597K', 'obs': '7.8'}
{'name': 'Piratas do Caribe: A Vingança de Salazar (2017) - IMDb', 'rate': '281K', 'obs': '6.5'}
{'name': 'Soul Surfer: Coragem de Viver (2011) - IMDb', 'rate': '48K', 'obs': '7.0'}
{'name': 'Top Gun: Ases Indomáveis (1986) - IMDb', 'rate': '311K', 'obs': '6.9'}
{'name': 'A Lista de Schindler (1993) - IMDb', 'rate': '1.3M', 'obs': '8.9'}


In [59]:
con.commit()

In [60]:
con.close()
cursor.close()

True

In [63]:
cursor.execute("SELECT * FROM filmes")

In [64]:
g = cursor.fetchall()

In [65]:
g

[('Dunkirk (2017) - IMDb', '597K', '7.8'),
 ('Piratas do Caribe: A Vingança de Salazar (2017) - IMDb', '281K', '6.5'),
 ('Soul Surfer: Coragem de Viver (2011) - IMDb', '48K', '7.0'),
 ('Top Gun: Ases Indomáveis (1986) - IMDb', '311K', '6.9'),
 ('A Lista de Schindler (1993) - IMDb', '1.3M', '8.9')]

Agora que inserimos dados na nossa base de dados podemos ler esses dados no python. Para isto, criaremos uma função para efetuar a leitura

In [31]:
import pandas as pd
def read_table(table):
    query = "SELECT * FROM " + table
    return pd.read_sql(query,con)

In [ ]:
con=mdb.connect(user='user', password ='passwd', database='aula')
cursor = con.cursor();

In [32]:
df = read_table('filmes')

/Users/gustavorsampaio/miniforge3/lib/python3.9/site-packages/pandas/io/sql.py:761: UserWarning: pandas only support SQLAlchemy connectable(engine/connection) ordatabase string URI or sqlite3 DBAPI2 connectionother DBAPI2 objects are not tested, please consider using SQLAlchemy
  warnings.warn(


In [33]:
df

name    rate   obs
0                                             Gustavo    1000     1
1                                                UFPE     100     2
2                                               Pedro     100     3
3                                               Sofia   10000     5
4                               Dunkirk (2017) - IMDb     7.8  648K
5   Piratas do Caribe: A Vingança de Salazar (2017...     6.5  309K
6         Soul Surfer: Coragem de Viver (2011) - IMDb     7.0   50K
7              Top Gun: Ases Indomáveis (1986) - IMDb     6.9  423K
8                  A Lista de Schindler (1993) - IMDb     9.0  1.3M
9                               Gustavo Sampaio TESTE  877767     5
10                              Gustavo Sampaio TESTE  877767     5
11                              Gustavo Sampaio TESTE  877767     5
12                              Gustavo Sampaio TESTE  877767     5

Por fim, podemos salvar uma base completa em SQL em um arquivo CSV se desejarmos. Mas lembre-se que é muito mais eficiente manter tudo em SQL

``mysql -u usuario -p aula -e "select * from filmes" -B > filmes_aula.csv``

In [138]:
con.close()
cursor.close()

True

In [36]:
import requests

In [ ]:
res = requests.get("http://gappe-covid19.org/")
r = res.content
print(r)

In [ ]:
res = requests.get("http://api.gappe-covid19.org/api/world_data/")
r = res.content
print(r)

In [35]:
import json

In [117]:
dados = json.loads(r)

In [118]:
dados

{'world_cases': {'data': {'datasets': [{'borderColor': ['#47b784'],
     'borderWidth': 3,
     'data': [0.38671373761499783,
      0.7135006685017472,
      1.3631357024229158,
      1.4629079334441237,
      1.753665606524177,
      1.939339030419692,
      2.1325343953877782,
      2.4679608771371724,
      2.6381830727754676,
      2.8225229471134314,
      2.9687543867900206,
      3.0773276660207283,
      3.1863431803628908,
      3.2626307915428665,
      3.3413478741072207,
      3.4028154515737263,
      3.4496766883328736,
      3.45804512575026,
      3.7493456131156306,
      3.8518169101626687,
      3.8823154489815486,
      3.9125496739146124,
      3.9394283863498787,
      3.963664971096462,
      3.9691477504026373,
      3.975266837473531,
      3.9815472726510848,
      4.000570992714676,
      4.0008436792631805,
      4.003682988068604,
      4.0103025806136685,
      4.015587354329542,
      4.021124283367497,
      4.025288628423719,
      4.030696642412862,
  

In [72]:
dados['world_cases']['data']['datasets'][2]

{'borderColor': ['#2471A3'],
 'borderWidth': 3,
 'data': [0.5945022959411338,
  0.9511772398798661,
  1.2696309709984008,
  1.5663628789700996,
  1.720513558797358,
  2.155150044205802,
  2.3782935955200117,
  2.675430826742548,
  3.141899239728519,
  3.5991235169123708,
  3.89429956316156,
  3.89429956316156,
  4.726234390234855,
  4.926331526748102,
  5.125308066640363,
  5.368208983752438,
  5.535123789416331,
  5.704048782015309,
  5.959754862866656,
  6.087465752901711,
  6.3051658037983636,
  6.430704434369167,
  6.630667021967023,
  6.75744108944305,
  6.973716430053223,
  7.12818730788674,
  7.256828853065091,
  7.3651142248502275,
  7.454841466306982,
  7.548277465516481,
  7.634986562373516,
  7.716965647416379,
  7.790519836175831,
  7.852235141414272,
  7.909055128265214,
  7.951557277967825,
  7.9890466208610205,
  8.026859299538282,
  8.07013843260317,
  8.103328626209665,
  8.135762166195907,
  8.165356607341018,
  8.188422100055332,
  8.207821396569726,
  8.222075665469

In [37]:
header={"Authorization": "563492ad6f917000010000019fc0e6ae4dfe410f957ed316681879b7"}
res = requests.get("https://api.pexels.com/v1/search?query=people", headers=header)
r = res.text
#rr = r.encode().decode('unicode_escape')

In [38]:
r

'{"page":1,"per_page":15,"photos":[{"id":2050994,"width":3648,"height":5472,"url":"https://www.pexels.com/photo/woman-standing-near-yellow-petaled-flower-2050994/","photographer":"Edu Carvalho","photographer_url":"https://www.pexels.com/@educarvalho","photographer_id":1026575,"avg_color":"#5A4B39","src":{"original":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg","large2x":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026dpr=2\\u0026h=650\\u0026w=940","large":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=650\\u0026w=940","medium":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=350","small":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=130","portrait":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compres

In [14]:
r

'{"page":1,"per_page":15,"photos":[{"id":2050994,"width":3648,"height":5472,"url":"https://www.pexels.com/photo/woman-standing-near-yellow-petaled-flower-2050994/","photographer":"Edu Carvalho","photographer_url":"https://www.pexels.com/@educarvalho","photographer_id":1026575,"avg_color":"#5A4B39","src":{"original":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg","large2x":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026dpr=2\\u0026h=650\\u0026w=940","large":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=650\\u0026w=940","medium":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=350","small":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compress\\u0026cs=tinysrgb\\u0026h=130","portrait":"https://images.pexels.com/photos/2050994/pexels-photo-2050994.jpeg?auto=compres

### Twitter e Facebook

Utilizaremos o [API tweepy](http://docs.tweepy.org/en/v3.5.0/api.html) para conectar ao tweeter

# conda install -c conda-forge tweepy

In [39]:
# conda install -c conda-forge tweepy

import tweepy
#import facebook # pip install facebook-sdk|

##### CRIAR BASE DE DADOS SQL

``CREATE DATABASE twitter
 USE twitter
 CREATE TABLE twitter (time TEXT NOT NULL, text TEXT NOT NULL, user_id TEXT NOT NULL, followers TEXT NOT NULL);``
 
 ``INSERT INTO twitter (time, text, user_id, followers) values ('4:54', 'alow', '567', '43')``

In [140]:
con=mdb.connect(user='gsampaio', password ='gsampaio1982', database='aula')
cursor = con.cursor();

Definir os tokens de acesso. Pode criar os tokens no [api do twitter](https://developer.twitter.com/en/docs.html)

In [141]:
ACCESS_TOKEN = '?'
ACCESS_SECRET = '?'
CONSUMER_KEY = '?'
CONSUMER_SECRET = '?'

In [40]:
ACCESS_TOKEN

'54274444-Mzk2xTba2pohO1LnSSAmrepdvWFgkDmBk9MyhbJcw'

Após definis os tokens de acesso, precisamos criar a conexão com o tweeter.

In [41]:
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)

In [42]:
auth

Podemos definir opções a nossa conexão com o API. Por exemplo, opções relacionadas a rate limits

**wait_on_rate_limit** – Whether or not to automatically wait for rate limits to replenish

**wait_on_rate_limit_notify** – Whether or not to print a notification when Tweepy is waiting for rate limits to replenish

In [43]:
api = tweepy.API(auth)
api.wait_on_rate_limit = True
api.wait_on_rate_limit_notify = True

Finalmente, podemos pesquisar todos os tweets relacionados a um termo. Podemos, também, definir o idioma dos tweets

In [45]:
for tweet in tweepy.Cursor(api.search, q='#PETR4' , lang= 'pt').items(): # geocode='5.29126,52.132633,150km'
    #print(tweet.created_at, tweet.text, tweet.user.id , tweet.user.followers_count)
    time = str(tweet.created_at)
    #time = '8947710'
    text = str(tweet.text)
    #text = 'poxa'
    user_id = str(tweet.user.id)
    #user_id = '7668'
    followers = str(tweet.user.followers_count)
    #followers = '765647'
    #insertstmt=("INSERT INTO twitter (time, text, user_id, followers) values ('%s', '%s', '%s', '%s')" % (time, text, user_id, followers))
    #cursor.execute(insertstmt)
    print(tweet.created_at, tweet.text, tweet.user.id , tweet.user.followers_count)

2022-09-26 18:51:45 Mais mencionadas agora / Sentimento geral / Participou

1º #PETR4 🔴 @Lejustfollows
2º #GFSA3 ⚪️ @Estoaresearch
3º… https://t.co/MPD7NCyOy0 1502002596147605511 2622
2022-09-26 18:20:13 Defasagem de preços. Gasolina e óleo Diesel (26/09/2022). Fonte: Abicom: https://t.co/Uf49eHpyTm #PETR4 #Petrobras… https://t.co/cUyuSFJ1X8 4549077863 61
2022-09-26 18:19:40 Defasagem de preços da gasolina e óleo Diesel (26/09/2022). Fonte: Abicom: https://t.co/Uf49eHpyTm #PETR4… https://t.co/ns3AC5szVQ 4549077863 61
2022-09-26 18:02:57 RT @fintwitbrtrends: Mais mencionadas agora / Sentimento geral / Participou

1º #IBOV 🔴 @NOALVOLUCIANO
2º #PETR4 ⚪️ @pauta_economica
3º #VA… 1068845028934647808 305
2022-09-26 17:59:45 Mais mencionadas agora / Sentimento geral / Participou

1º #IBOV 🔴 @NOALVOLUCIANO
2º #PETR4 ⚪️ @pauta_economica
3º… https://t.co/DM9N0dO2xh 1502002596147605511 2622
2022-09-26 17:52:45 #PETR4 -2,08% acionou o pivô de baixa.

Curto prazo tendência de baixa e mantém expecta

In [42]:
con.commit()
con.close()

In [ ]:
con=mdb.connect(user='UserName', password ='PassWord', database='twitter')
cursor = con.cursor();

Pode-se fazer a pesquisa por coordenadas geográficas e um raio

In [46]:
for tweet in tweepy.Cursor(api.search, q='Assalto' , geocode='-8.05428,-34.8813,50km').items():
    #print(tweet.created_at, tweet.text, tweet.user.id , tweet.user.followers_count)
    time = str(tweet.created_at)
    #time = '8947710'
    text = str(tweet.text)
    #text = 'poxa'
    user_id = str(tweet.user.id)
    #user_id = '7668'
    followers = str(tweet.user.followers_count)
    #followers = '765647'
    #insertstmt=("INSERT INTO twitter (time, text, user_id, followers) values ('%s', '%s', '%s', '%s')" % (time, text, user_id, followers))
    #cursor.execute(insertstmt)
    print(tweet.created_at, tweet.text, tweet.user.id , tweet.user.followers_count)

2022-09-26 18:18:54 @sabinogabriel_ um cavalo quando eu era criança quase me matou foi loucura e outra quando eu tava no pão de açúcar… https://t.co/WurZ3o4X8O 1171393026696105986 229
2022-09-26 17:07:04 @centraldamem Todo mundo com ingressos já central,só biscoitando na azul e na latm por promo de passagens, tá um assalto a mão armada 105235318 1058
2022-09-26 16:04:33 Eu mesma cancelaria o assalto na hora onde ja se viu um absurdo desses https://t.co/kM1rPPdq3f 736247544657924096 174
2022-09-26 12:00:35 @VEJA @radaronline Arriscada e mal planejada foi a estratégia de GOLPE da MÍDIA GOLPISTA, tomaram o país de assalto… https://t.co/rSjQ76p1S3 48992982 3829
2022-09-26 11:02:55 @peterjordan100 Reagi a um assalto e to vivo 1842866850 93
2022-09-26 09:07:28 @ECantanhede Então a senhora afirma categoricamente que a racionalidade é ter um LADRÃO no governo do nosso país, q… https://t.co/98rK8aFfAi 958459834940166149 83
2022-09-26 08:55:55 @marciatiburi @GuilhermeBoulos Vc, @marciatiburi , d

Pegar Tweets de um pais USA

In [14]:
places = api.geo_search(query="USA", granularity="country")
place_id = places[0].id
print(place_id)

96683cc9126741d1


In [15]:
place_id

'96683cc9126741d1'

In [16]:
tweets = api.search(q="place:%s" % place_id)

In [25]:
tweets[0]

Status(_api=<tweepy.api.API object at 0x1074e56d0>, _json={'created_at': 'Fri Oct 15 18:29:45 +0000 2021', 'id': 1449080068505022467, 'id_str': '1449080068505022467', 'text': 'I just gave 5 stars to Kelsey at @realhomechef for great service!', 'truncated': False, 'entities': {'hashtags': [], 'symbols': [], 'user_mentions': [{'screen_name': 'realhomechef', 'name': 'Home Chef', 'id': 1623326396, 'id_str': '1623326396', 'indices': [33, 46]}], 'urls': []}, 'metadata': {'iso_language_code': 'en', 'result_type': 'recent'}, 'source': '<a href="http://twitter.com/download/iphone" rel="nofollow">Twitter for iPhone</a>', 'in_reply_to_status_id': None, 'in_reply_to_status_id_str': None, 'in_reply_to_user_id': None, 'in_reply_to_user_id_str': None, 'in_reply_to_screen_name': None, 'user': {'id': 40871203, 'id_str': '40871203', 'name': 'Jeremy D. Boyd', 'screen_name': 'jeremydboyd', 'location': 'Miami, FL', 'description': '#BESTOFMIAMI ®️ 📈 #1 Digital Marketing 🔊 Advertising 📊 SEO/SEM/PRO @Google P

In [26]:
for tweet in tweets:
    print(tweet.text + " | " + tweet.place.name if tweet.place else "Undefined place")

I just gave 5 stars to Kelsey at @realhomechef for great service! | Miami
@lil_B_lit Lol fr | East Stroudsburg
@raty0303 🤣🤣🤣 | Boston
@Samdfriedman226 @CarlyCaramanna Those are so cute! | New Albany
Like a boss being a profesional 💪✌🏽💥 #bellator268 #mma #skillsetmgmt #ukfgym #mmalab @ Footprint Center https://t.co/EBOryxzxRm | Phoenix
Once i start taking Jameson shots back to back. TAKE ME HOME https://t.co/UqVVucA62L | Eidson Road
@pulte @mari15050 $DermontWR | Fort Worth
Yes. Died even. https://t.co/0wfIyffP6U | Memphis
@BocqWilliam 💯😉👍😄 | Fort Worth
@cw_fudge 😂😂😂 | Hailey
@jASZiLOVE 👀 | Sacramento
Twitter Could Soon Start Showing Ads in the Middle of Conversations
https://t.co/1JSG7BMIbG | West Virginia
So close no matter how far | Los Angeles
@giupuyola @lherrero Cesco de Arecibo estuve 10mts           
(2 sellos, recibo de agua o luz, llenar dos formularios y Cert de nacimiento) | Trujillo Alto
i should be a business owner by now. it’s solely my fault. 🥴 https://t.co/4ZDwUHWgRT | 

Pegar Tweets de um pais Brasil

In [27]:
places = api.geo_search(query="BRAZIL", granularity="country")
place_id = places[0].id
print(place_id)

1b107df3ccc0aaa1


In [28]:
tweets = api.search(q="place:%s" % place_id)
for tweet in tweets:
    print(tweet.text + " | " + tweet.place.name if tweet.place else "Undefined place")

Vaza @SergioSRoficial https://t.co/UvZ7j961HG | Itaúna
Quando olha essa imagem, qual a frase que vem na sua cabeça? https://t.co/wGyLpe1IVh | São Luís
@BFFDaDems NUNCA TE REJEITE FDP 😤 | Mantenópolis
@eujucesar Eu li isso aqui e me veio o meme
"Bicha se eu me virar"
E eu ri, desculpa hahahahaha | Belém
Oi Deus sou eu denovo, ajuda meu pai criar juízo 🙏 | Boa Esperança
@cesaramferreira Só não sei se foi pro rica ou pro pilhado kkkkk | Birigui
dar uma volta no point hoje | São Gonçalo
Amo este vídeo 😂😂😂😂🗣🗣🗣 https://t.co/R3s2beLkWL | Curitiba
@LucianoHuck LUCIANO HUCK NO ANO DE 2007 VIROU UMA FAVELINHA MAS SUJOU A CIDADE COM MUITOS VAGABUNDOS NA RUA ROUBAN… https://t.co/wjXZAcYAW5 | Queimados
Nenhum dos dois tem madrinha. 
Exatamente pq as pessoas socam a consideração no olho do cu delas. A questão nunca s… https://t.co/AYI1OwomIU | Rio de Janeiro
#AQueda qual é a graça ? 🤐😠👿 imaginei 🤔😈 que você perguntaria 😡👹👹👹é que pensei 🤡🤔 em uma piada 👀👹🤡 só que vc não en… https://t.co/g6yw4Ybfhm | 

In [ ]:
ACCESS_TOKEN = '54274444-Mzk2xTba2pohO1LnSSAmrepdvWFgkDmBk9MyhbJcw'
ACCESS_SECRET = 'd5InI2E4L2hDj2en2qzoMQtu6xwVwkCKmk4TEx60x1woy'
CONSUMER_KEY = 'p8DMQP2Yc3mK8eDI63Ac2X4jr'
CONSUMER_SECRET = 'lzXSHFAA77jnm4UhXRAzKVN1VISYbnGQTyGKLvn19haDebaYNf'

# Pandas e Numpy

Pandas e NumPy são duas bibliotecas muito importantes para se trabalhar com dados no python.

A biblioteca NumPy que é bastante utilizada na academia para programação numérica

Já o Pandas é utilizado predominantemente para Data Visualization e para Data Analysis


In [29]:
import numpy as np

#### Vetorização

NumPy é excelente para operações com vetores.

Operações do tipo:

- multiplicação matricial e outras operações de álgebra linear  
- vetores de número aleatório  
- aplicação de transformação (ex., seno e cosseno)

Vamos tentar criar duas matrizes utilizando listas. Uma 3 x 3 e outra um vetor 1 x 3:

In [30]:
a = [[5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]]

In [31]:
a

[[5, 1, 3], [1, 1, 1], [1, 2, 1]]

In [32]:
b = [1, 2, 3]

In [34]:
b

[1, 2, 3]

In [35]:
print(a*b)

TypeError: can't multiply sequence by non-int of type 'list'

In [5]:
a = [[5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]]
b = [1, 2, 3]
print(a)
print(b)
print(a*b)

[[5, 1, 3], [1, 1, 1], [1, 2, 1]]
[1, 2, 3]


TypeError: can't multiply sequence by non-int of type 'list'

In [39]:
np.array(a)

array([[5, 1, 3],
       [1, 1, 1],
       [1, 2, 1]])

In [42]:
np.array(b)

array([1, 2, 3])

In [44]:
type(np.array(2))

numpy.ndarray

Como podemos observar não conseguimos multiplicar essas duas listas. Analisando o erro fica claro que não podemos multiplicar uma lista por uma outra lista.

#### NumPy Arrays

A coisa mais importante que o NumPy define é um **array** N-dimensional formalmente denominado de [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

Podemos, então, recriar os vetores *a e b* como NumPy arrays e obter sua multiplicação da seguinte maneira:

In [46]:
a = np.array([[ 5, 1 ,3], [ 1, 1 ,1], [ 1, 2 ,1]])
b = np.array([1, 2, 3])

In [47]:
a

array([[5, 1, 3],
       [1, 1, 1],
       [1, 2, 1]])

In [48]:
b

array([1, 2, 3])

In [49]:
a*b

array([[5, 2, 9],
       [1, 2, 3],
       [1, 4, 3]])

In [50]:
print(a*b)

[[5 2 9]
 [1 2 3]
 [1 4 3]]


In [53]:
a[0][0]

5

Observe, porém, que a multiplicação foi realizada elemento por elemento.

Não obtivemos uma multiplicação matricial. Voltaremos a este problema mais tarde

NumPy arrays são parecidos com listas exceto que:

- As entradas devem ser *homogeneas* (elementos do mesmo tipo)  
- Esses tipos devem ser um dos tipos (`dtypes`) suportados pelo NumPy  


Os tipos mais importantes são:

- float64: 64 bit número em ponto flutuante  
- int64: 64 bit inteiro  
- bool:  8 bit True ou False  

Podemos obter o tipo de um objeto da seguinte maneira:

In [55]:
type(a[0][0])

numpy.int64

In [56]:
a.dot(b)

array([16,  6,  8])

Para se obter a multiplicação matricial, devemod utilizar ".dot". Por exemplo:

In [20]:
print(a.dot(b))

[16  6  8]


Ainda assim nossa multiplicação não esta correta dado que estamos multiplicando uma matrix 3 x 3 por uma 1 x 3.

Redefinindo *b* da forma correta podemos obter a multiplicação matricial:

In [59]:
b = np.array([[1], [2], [3]])

In [60]:
b

array([[1],
       [2],
       [3]])

In [61]:
a.dot(b)

matrix([[16],
        [ 6],
        [ 8]])

Há uma outra maneira de se definir uma matriz. Essa envolve a utilização de [numpy.matrix](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matrix.html)

Definindo-se dessa maneira as matrizes, podemos utilizar a operação produto (*), para multiplica-las:

In [62]:
a = np.matrix('[5, 1 ,3; 1, 1 ,1; 1, 2 ,1]')
b = np.matrix('[1; 2; 3]')

In [65]:
print(a)

[[5 1 3]
 [1 1 1]
 [1 2 1]]


In [66]:
b

matrix([[1],
        [2],
        [3]])

In [67]:
a * b

matrix([[16],
        [ 6],
        [ 8]])

In [68]:
a

matrix([[5, 1, 3],
        [1, 1, 1],
        [1, 2, 1]])

Podemos obter a transposta de diferentes maneiras:

In [69]:
a.transpose()

matrix([[5, 1, 1],
        [1, 1, 2],
        [3, 1, 1]])

In [72]:
a.T

matrix([[5, 1, 1],
        [1, 1, 2],
        [3, 1, 1]])

In [74]:
n1 = "{:e}".format(12300000)

In [75]:
n1

'1.230000e+07'

In [77]:
print(format(float(n1), 'f'))

12300000.000000


In [83]:
np.set_printoptions(suppress=True, formatter={'float_kind':'{:f}'.format})

In [84]:
a.I

matrix([[0.500000, -2.500000, 1.000000],
        [-0.000000, -1.000000, 1.000000],
        [-0.500000, 4.500000, -2.000000]])

In [71]:
a.I

matrix([[ 5.00000000e-01, -2.50000000e+00,  1.00000000e+00],
        [-3.08395285e-17, -1.00000000e+00,  1.00000000e+00],
        [-5.00000000e-01,  4.50000000e+00, -2.00000000e+00]])

E a Inversa de uma matriz

In [85]:
a.getI()

matrix([[0.500000, -2.500000, 1.000000],
        [-0.000000, -1.000000, 1.000000],
        [-0.500000, 4.500000, -2.000000]])

No mais, NumPy arrays podem ser criados a partir de listas utilizando np.array

In [76]:
np.array([10, 20])

array([10, 20])

##### Métodos em um Array

In [86]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [87]:
a.sort()
a

array([1, 2, 3, 4])

In [88]:
a.sum()

10

In [89]:
a.mean()

2.5

In [90]:
a.max()

4

In [91]:
a.min()

1

In [92]:
a.cumsum()

array([ 1,  3,  6, 10])

In [3]:
import pandas as pd

Podemos ler um arquivo em formato CSV, por exemplo, e transforma-lo em uma base.

In [68]:
df1 = pd.read_csv("filmes.csv", header = None, names=['nome', 'obs', 'rate']) 

In [86]:
df1

nome        obs  rate
0                              Dunkirk (2017) - IMDb    478.157   7.9
1  Piratas do Caribe: A Vinganca de Salazar (2017...    233.668   6.6
2        Soul Surfer: Coragem de Viver (2011) - IMDb     42.150   7.0
3             Top Gun: Ases Indomaveis (1986) - IMDb    267.415   6.9
4                 A Lista de Schindler (1993) - IMDb  1.105.130   8.9

Salvar uma base de dados em csv.

In [88]:
df1.to_csv('save_filmes.csv')

O mesmo pode-se aplicar para o [pickle](). Podemos ler e salvar bases de dados em pickle

In [ ]:
pd.read_pickle("filmes.pkl")

In [90]:
pd.to_pickle("filmes.pkl")

Ou gerar uma base de dados com números aleatórios 

In [57]:
df1 = pd.DataFrame(np.random.randn(10, 5))

In [58]:
df1

0         1         2         3         4
0 -0.138971 -0.474679 -1.683489  0.775442 -0.202018
1  0.561367  0.277423 -0.485886  0.004307 -1.153390
2  0.258708  0.172462  0.944909 -0.150567  1.840518
3 -0.542672 -0.897579 -1.223496  0.707532 -0.801211
4 -0.136000 -0.192846 -1.064098  1.779197  1.440163
5  0.472424  2.412187  0.223163  0.582452  0.577441
6 -0.041464 -0.126405  3.787206  1.980905  1.240318
7  0.345998  0.528852  0.623386 -0.183449 -0.515452
8  0.353237  0.427501 -0.491137 -0.594328 -1.044061
9 -0.788651  0.981514  1.090212 -0.755600  0.436531

Array 10-por-5 de amostras de uma N(0, 1):

In [63]:
np.random.randn(10, 5)

array([[-0.78154506,  0.68314539,  0.23714728, -0.95826529,  0.37489086],
       [-0.28715178, -0.94707705,  0.43128177, -0.03033668, -0.61364148],
       [ 0.71141149,  1.48044133, -0.37608486,  0.04843216,  0.73452824],
       [ 0.20849167,  0.61363224, -0.90290758,  0.35157061,  0.09602804],
       [ 0.62781702, -0.46359791, -0.45712359, -1.57732305,  0.70397232],
       [ 0.29520243, -1.21995187,  0.33977456,  0.51318333,  0.91849793],
       [-0.21219942, -0.03598982,  0.88980474, -0.45334625, -1.36566396],
       [-0.96174959,  0.31688792, -0.23588552,  2.27724765,  0.1220765 ],
       [-0.53840215,  1.09556642,  0.97134686, -0.15733721,  0.52716582],
       [-0.7428618 , -0.9996836 ,  1.56608427, -0.23948601, -0.0638905 ]])

Array 10-por-5 de amostras de uma N(3, 6.25):

In [64]:
2.5 * np.random.randn(10, 5) + 3

array([[ 2.47506596,  3.68037733,  1.50840621,  3.04053642, -1.82247211],
       [ 5.22469801,  0.01595204,  4.81542769, -2.36689982,  2.20408174],
       [ 3.20060139,  5.25475018,  2.24659112,  3.13219301,  6.50634299],
       [ 3.81889475,  1.3344354 ,  7.51834086,  0.39100812,  5.30315293],
       [10.05032813,  5.71095601,  0.20681575,  2.52130612,  4.30648805],
       [ 9.02190372, -2.81977265, -0.17268192,  4.83042246,  0.48429875],
       [ 4.0614867 ,  2.87838915,  0.36287758,  6.57851012,  3.06382818],
       [ 0.57489661,  1.24389835,  1.36665315,  9.09077566,  5.12342204],
       [ 4.38208607,  4.65599378,  1.43346843,  3.01271328,  3.75195167],
       [ 5.11171031,  2.68838734,  2.82096222,  3.84325145,  4.60075771]])

In [1]:
data = {
'País': ['Bélgica', 'Índia', 'Brasil'],
'Capital': ['Bruxelas', 'Nova Delhi', 'Brasília'],
'População': [123465, 456789, 987654]
}

In [4]:
df = pd.DataFrame(data, columns=['País','Capital','População'])

In [5]:
df

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

In [154]:
df.drop([0, 1])

País   Capital  População
2  Brasil  Brasília     987654

Removendo colunas utilizando o argumento axis=1

In [153]:
df.drop('País', axis=1)

Capital  População
0    Bruxelas     123465
1  Nova Delhi     456789
2    Brasília     987654

Coletando informações básicas sobre o DataFrame: 

Quantidade de linhas e colunas do DataFrame

In [155]:
df.shape

(3, 3)

Descrição do Index

In [156]:
df.index 

RangeIndex(start=0, stop=3, step=1)

Colunas presentes no DataFrame

In [157]:
df.columns 

Index(['País', 'Capital', 'População'], dtype='object')

Contagem de dados não-nulos

In [158]:
df.count()

País         3
Capital      3
População    3
dtype: int64

Criando uma nova coluna em um DataFrame

In [159]:
df['Nova Coluna'] = 0

In [160]:
df

País     Capital  População  Nova Coluna
0  Bélgica    Bruxelas     123465            0
1    Índia  Nova Delhi     456789            0
2   Brasil    Brasília     987654            0

Renomeando colunas de um DataFrame

Se seu DataFrame possui 3 colunas, passe 3 novos valores em uma lista

In [162]:
df.columns = ['Coluna 1', 'Coluna 2', 'Coluna 3', 'Coluna 4']

In [163]:
df

Coluna 1    Coluna 2  Coluna 3  Coluna 4
0  Bélgica    Bruxelas    123465         0
1    Índia  Nova Delhi    456789         0
2   Brasil    Brasília    987654         0

Resumo dos dados

Soma dos valores de um DataFrame

In [ ]:
df.sum()

Menor valor de um DataFrame

In [ ]:
df.min()

Maior valor

In [ ]:
df.max()

Index do menor valor

In [ ]:
df.idmin()

Index do maior valor

In [ ]:
df.idmax()

Resumo estatístico do DataFrame, com quartis, mediana, etc.

In [ ]:
df.describe()

Média dos valores

In [ ]:
df.mean()

Mediana dos valores

In [ ]:
df.median()

Aplicando funções:

Aplicando uma função que substitui a por b

In [8]:
df.apply(lambda x: x.replace('a', 'b'))

País     Capital  População
0  Bélgica    Bruxelas     123465
1    Índia  Nova Delhi     456789
2   Brasil    Brasília     987654

Ordenando valores:

Ordenando em ordem crescente

In [168]:
df.sort_values(by='Coluna 3')

Coluna 1    Coluna 2  Coluna 3  Coluna 4
0  Bélgica    Bruxelas    123465         0
1    Índia  Nova Delhi    456789         0
2   Brasil    Brasília    987654         0

Ordenando em ordem decrescente

In [170]:
df.sort_values(by='Coluna 3',ascending=False)

Coluna 1    Coluna 2  Coluna 3  Coluna 4
2   Brasil    Brasília    987654         0
1    Índia  Nova Delhi    456789         0
0  Bélgica    Bruxelas    123465         0

Selecionando valores: 

Selecionando a primeira linha da coluna país

In [172]:
df.loc[0, 'Coluna 1']

'Bélgica'